#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <esp_timer.h>
#include "app_config.h"
#include "sd_logger.h"
#include "vesc_protocol.h"
using namespace app_config;
namespace {
WebServer web(kHttpPort); HardwareSerial vescUart(1); vlog::Logger logger; vesc::Parser parser; vesc::FirmwareInfo fw; vesc::Values values;
uint32_t lastSystemMs=0,lastSerialMs=0; uint64_t bootUs=0,lastRequestUs=0,nextFwUs=0; bool fwWaiting=false,valuesWaiting=false,sessionArmed=false,summaryPending=false,controlArmed=false,pulseActive=false; uint64_t armUntilUs=0,pulseEndUs=0,fastValuesUntilUs=0; uint32_t pulseCount=0,estopCount=0; uint32_t summaryTryMs=0,packetSequence=0,uartBytes=0,fwRequests=0,fwResponses=0,valuesRequests=0,valuesResponses=0,crcErrors=0,framingErrors=0,lengthErrors=0,parseErrors=0,unexpected=0,timeouts=0,rawDrops=0,parsedDrops=0; uint64_t rttSumUs=0,rttMaxUs=0,lastResponseUs=0,lastValuesUs=0,nextValuesUs=0,lastValuesRequestUs=0;
void put16(uint8_t*&p,uint16_t v){*p++=v>>8;*p++=v;}void put32(uint8_t*&p,uint32_t v){for(int i=3;i>=0;i--)*p++=(uint8_t)(v>>(8*i));}void put64(uint8_t*&p,uint64_t v){for(int i=7;i>=0;i--)*p++=(uint8_t)(v>>(8*i));}
bool enqueue(const vlog::Event&e,bool raw){bool ok=logger.enqueue(e);if(!ok&&logger.isLogging()){if(raw)rawDrops++;else parsedDrops++;}return ok;}
void logRaw(const vesc::Frame&f,vesc::ParseError err,uint64_t requestUs,uint32_t rtt){const uint32_t ps=++packetSequence;vlog::Event h{};h.type=vlog::Type::RawHeader;h.flags=(f.crcOk?1:0)|(f.endOk?2:0);h.rxUs=f.receivedUs;h.requestUs=requestUs;h.roundTripUs=rtt;h.packetSequence=ps;uint8_t*p=h.payload;*p++=f.command;*p++=f.start;put16(p,f.payloadLength);put16(p,f.receivedCrc);put16(p,f.calculatedCrc);*p++=(uint8_t)err;enqueue(h,true);for(uint16_t off=0;off<f.payloadLength;){const uint16_t n=(uint16_t)min((size_t)110,(size_t)(f.payloadLength-off));vlog::Event b{};b.type=vlog::Type::RawBlock;b.rxUs=f.receivedUs;b.requestUs=requestUs;b.roundTripUs=rtt;b.packetSequence=ps;p=b.payload;put32(p,ps);put16(p,off);put16(p,n);memcpy(p,f.payload+off,n);enqueue(b,true);off+=n;}}
void logValues(const vesc::Frame&f,uint64_t req,uint32_t rtt){vlog::Event e{};e.type=vlog::Type::Values;e.flags=values.valid?1:0;e.rxUs=f.receivedUs;e.requestUs=req;e.roundTripUs=rtt;e.packetSequence=packetSequence;uint8_t*p=e.payload;auto pf=[&](float x){memcpy(p,&x,4);p+=4;};pf(values.mosTempC);pf(values.motorTempC);pf(values.motorCurrentA);pf(values.inputCurrentA);pf(values.inputVoltageV);pf(values.duty);pf(values.erpm);pf(values.ampHours);pf(values.ampHoursCharged);pf(values.wattHours);pf(values.wattHoursCharged);put32(p,(uint32_t)values.tachometer);put32(p,(uint32_t)values.tachometerAbs);*p++=values.fault;*p++=f.payloadLength;enqueue(e,false);}void logFw(const vesc::Frame&f,uint64_t requestUs,uint32_t rtt){vlog::Event e{};e.type=vlog::Type::FwInfo;e.flags=fw.valid?1:0;e.rxUs=f.receivedUs;e.requestUs=requestUs;e.roundTripUs=rtt;e.packetSequence=packetSequence;uint8_t*p=e.payload;*p++=fw.major;*p++=fw.minor;*p++=f.payloadLength;size_t n=strnlen(fw.hardwareName,sizeof(fw.hardwareName));*p++=(uint8_t)n;memcpy(p,fw.hardwareName,n);p+=n;n=strnlen(fw.firmwareName,sizeof(fw.firmwareName));*p++=(uint8_t)n;memcpy(p,fw.firmwareName,n);p+=n;*p++=fw.uuidValid?1:0;if(fw.uuidValid)memcpy(p,fw.uuid,12);enqueue(e,false);}
void handleFrame(const vesc::Frame&f,vesc::ParseError err){const bool isFw=f.command==vesc::kCommFwVersion;const bool isValues=f.command==vesc::kCommGetValues;const uint64_t requestUs=isFw&&fwWaiting?lastRequestUs:(isValues&&valuesWaiting?lastValuesRequestUs:0);const uint32_t rtt=requestUs?(uint32_t)(f.receivedUs-requestUs):0;logRaw(f,err,requestUs,rtt);if(!f.crcOk){crcErrors++;return;}if(!f.endOk){framingErrors++;return;}if(isFw){fwWaiting=false;fwResponses++;lastResponseUs=f.receivedUs;if(!vesc::Parser::parseFirmware(f,fw))parseErrors++;logFw(f,requestUs,rtt);}else if(isValues){valuesWaiting=false;valuesResponses++;lastValuesUs=f.receivedUs;if(!vesc::Parser::parseCurrentValues(f,values)){parseErrors++;}else logValues(f,requestUs,rtt);}else{unexpected++;return;}rttSumUs+=rtt;if(rtt>rttMaxUs)rttMaxUs=rtt;}
void drainUart(){vesc::Frame f{};vesc::ParseError e;while(vescUart.available()>0){uint8_t b=(uint8_t)vescUart.read();uartBytes++;if(parser.feed(b,esp_timer_get_time(),f,e))handleFrame(f,e);else if(e==vesc::ParseError::Length)lengthErrors++;}if(parser.timeout(esp_timer_get_time(),e)){framingErrors++;}}
void sendFwRequest(){const uint8_t payload[]={vesc::kCommFwVersion};const uint16_t c=vesc::Parser::crc16(payload,sizeof(payload));uint8_t packet[]={0x02,0x01,vesc::kCommFwVersion,(uint8_t)(c>>8),(uint8_t)c,0x03};if(vescUart.write(packet,sizeof(packet))==sizeof(packet)){lastRequestUs=esp_timer_get_time();fwWaiting=true;fwRequests++;}else{timeouts++;nextFwUs=esp_timer_get_time()+(uint64_t)kFwRetryIntervalMs*1000ULL;}}
void logControl(uint8_t action,int32_t duty100k){vlog::Event e{};e.type=vlog::Type::CommStatus;e.flags=action;e.rxUs=esp_timer_get_time();uint8_t*p=e.payload;*p++=action;put32(p,(uint32_t)duty100k);put32(p,pulseCount);put32(p,estopCount);enqueue(e,false);}
bool sendDuty100k(int32_t duty100k){uint8_t payload[5]={vesc::kCommSetDuty,(uint8_t)((uint32_t)duty100k>>24),(uint8_t)((uint32_t)duty100k>>16),(uint8_t)((uint32_t)duty100k>>8),(uint8_t)duty100k};uint16_t crc=vesc::Parser::crc16(payload,sizeof(payload));uint8_t packet[10]={0x02,0x05,payload[0],payload[1],payload[2],payload[3],payload[4],(uint8_t)(crc>>8),(uint8_t)crc,0x03};return vescUart.write(packet,sizeof(packet))==sizeof(packet);}
void servicePulse(){if(!pulseActive)return;uint64_t now=esp_timer_get_time();if(now>=pulseEndUs){sendDuty100k(0);logControl(3,0);pulseActive=false;controlArmed=false;}}
void emergencyStop(){sendDuty100k(0);if(pulseActive)logControl(4,0);pulseActive=false;controlArmed=false;armUntilUs=0;++estopCount;}
void armPulse(){if(!logger.isLogging()||!fw.valid||!values.valid||values.fault!=0||pulseActive){web.send(409,"application/json","{\"error\":\"log, valid VESC values and fault=0 are required\"}");return;}controlArmed=true;armUntilUs=esp_timer_get_time()+(uint64_t)kArmWindowMs*1000ULL;logControl(1,0);web.send(200,"application/json","{\"armed\":true}");}
void pulseMotor(){uint64_t now=esp_timer_get_time();if(!logger.isLogging()||!controlArmed||now>armUntilUs||pulseActive||values.fault!=0){controlArmed=false;web.send(409,"application/json","{\"error\":\"not armed, expired, active, or fault\"}");return;}int32_t duty100k=(int32_t)(kPulseDuty*100000.0f);if(!sendDuty100k(duty100k)){web.send(503,"application/json","{\"error\":\"UART write failed\"}");return;}pulseActive=true;controlArmed=false;pulseEndUs=now+(uint64_t)kPulseDurationMs*1000ULL;fastValuesUntilUs=pulseEndUs+1000000ULL;nextValuesUs=now;++pulseCount;logControl(2,duty100k);web.send(202,"application/json","{\"pulse\":\"started\"}");}
void estopMotor(){emergencyStop();web.send(200,"application/json","{\"estop\":true}");}
void sendValuesRequest(){const uint8_t payload[]={vesc::kCommGetValues};const uint16_t c=vesc::Parser::crc16(payload,sizeof(payload));uint8_t packet[]={0x02,0x01,vesc::kCommGetValues,(uint8_t)(c>>8),(uint8_t)c,0x03};if(vescUart.write(packet,sizeof(packet))==sizeof(packet)){lastValuesRequestUs=esp_timer_get_time();valuesWaiting=true;valuesRequests++;}else timeouts++;}void serviceStage1B(){if(!logger.isLogging())return;const uint64_t now=esp_timer_get_time();if(!sessionArmed){sessionArmed=true;fw={};values={};fwWaiting=valuesWaiting=false;fwRequests=fwResponses=valuesRequests=valuesResponses=crcErrors=framingErrors=lengthErrors=parseErrors=unexpected=timeouts=rawDrops=parsedDrops=0;rttSumUs=rttMaxUs=lastResponseUs=lastValuesUs=lastValuesRequestUs=0;nextFwUs=now;nextValuesUs=0;}if(!fw.valid){if(fwRequests>=kFwMaxRequests)return;if(fwWaiting){if(now-lastRequestUs>(uint64_t)kVescResponseTimeoutMs*1000ULL){fwWaiting=false;timeouts++;nextFwUs=now+(uint64_t)kFwRetryIntervalMs*1000ULL;}return;}if(now>=nextFwUs)sendFwRequest();return;}if(valuesWaiting){if(now-lastValuesRequestUs>(uint64_t)kVescResponseTimeoutMs*1000ULL){valuesWaiting=false;timeouts++;nextValuesUs=now+(uint64_t)kVescRequestIntervalMs*1000ULL;}return;}if(now>=nextValuesUs){sendValuesRequest();nextValuesUs=now+(now<fastValuesUntilUs?20000ULL:(uint64_t)kVescRequestIntervalMs*1000ULL);}}
void systemLog(){if(!logger.isLogging()||millis()-lastSystemMs<kSystemIntervalMs)return;lastSystemMs=millis();vlog::Event e{};e.type=vlog::Type::SystemStatus;e.rxUs=esp_timer_get_time();uint8_t*p=e.payload;put32(p,uartBytes);put32(p,fwRequests);put32(p,fwResponses);put32(p,valuesRequests);put32(p,valuesResponses);put32(p,timeouts);put32(p,crcErrors);put32(p,framingErrors);put32(p,parseErrors);put32(p,rawDrops+parsedDrops);put32(p,logger.stats().writeErrors);put32(p,ESP.getFreeHeap());enqueue(e,false);}
void floatJson(char*out,size_t n,float v,bool valid,uint8_t decimals){if(!valid||!isfinite(v))snprintf(out,n,"null");else snprintf(out,n,"%.*f",decimals,v);}
void api(){
  const auto&s=logger.stats();const uint64_t now=esp_timer_get_time();
  char fwText[20],fwAge[16],valuesAge[16],mos[20],motor[20],motorCurrent[20],inputCurrent[20],inputVoltage[20],duty[20],erpm[20],json[1800];
  snprintf(fwText,sizeof(fwText),fw.valid?"%u.%u":"waiting",fw.major,fw.minor);
  if(lastResponseUs)snprintf(fwAge,sizeof(fwAge),"%llu",(unsigned long long)((now-lastResponseUs)/1000ULL));else snprintf(fwAge,sizeof(fwAge),"null");
  if(lastValuesUs)snprintf(valuesAge,sizeof(valuesAge),"%llu",(unsigned long long)((now-lastValuesUs)/1000ULL));else snprintf(valuesAge,sizeof(valuesAge),"null");
  floatJson(mos,sizeof(mos),values.mosTempC,values.valid,1);floatJson(motor,sizeof(motor),values.motorTempC,values.valid,1);floatJson(motorCurrent,sizeof(motorCurrent),values.motorCurrentA,values.valid,2);floatJson(inputCurrent,sizeof(inputCurrent),values.inputCurrentA,values.valid,2);floatJson(inputVoltage,sizeof(inputVoltage),values.inputVoltageV,values.valid,1);floatJson(duty,sizeof(duty),values.duty,values.valid,4);floatJson(erpm,sizeof(erpm),values.erpm,values.valid,0);
  snprintf(json,sizeof(json),"{\"stage\":\"2\",\"tx_allowed\":true,\"allowed_commands\":\"COMM_FW_VERSION, COMM_GET_VALUES; guarded COMM_SET_DUTY only\",\"vesc_detected\":%s,\"baud\":%lu,\"tx_gpio\":%d,\"rx_gpio\":%d,\"fw\":\"%s\",\"hardware\":\"%s\",\"firmware_name\":\"%s\",\"fw_age_ms\":%s,\"values_age_ms\":%s,\"values_valid\":%s,\"response_hz\":%.2f,\"erpm\":%s,\"duty\":%s,\"motor_current_a\":%s,\"input_current_a\":%s,\"input_voltage_v\":%s,\"mos_temp_c\":%s,\"motor_temp_c\":%s,\"fault\":%u,\"control_armed\":%s,\"pulse_active\":%s,\"pulse_duty\":%.3f,\"pulse_duration_ms\":%lu,\"pulse_count\":%lu,\"estop_count\":%lu,\"crc_errors\":%lu,\"timeouts\":%lu,\"parse_errors\":%lu,\"rtt_max_us\":%llu,\"fw_requests\":%lu,\"fw_responses\":%lu,\"values_requests\":%lu,\"values_responses\":%lu,\"uart_bytes_boot\":%lu,\"sd\":\"%s\",\"run\":\"%s\",\"queue\":%lu,\"qmax\":%lu,\"drops\":%lu,\"sd_errors\":%lu,\"normal_stop\":%s,\"fault_text\":\"%s\"}",
    fw.valid?"true":"false",(unsigned long)kVescUartBaud,kVescUartTxPin,kVescUartRxPin,fwText,fw.valid?fw.hardwareName:"not received",fw.valid?fw.firmwareName:"not received",fwAge,valuesAge,values.valid?"true":"false",valuesResponses?1.0f:0.0f,erpm,duty,motorCurrent,inputCurrent,inputVoltage,mos,motor,values.fault,controlArmed?"true":"false",pulseActive?"true":"false",kPulseDuty,(unsigned long)kPulseDurationMs,(unsigned long)pulseCount,(unsigned long)estopCount,(unsigned long)crcErrors,(unsigned long)timeouts,(unsigned long)parseErrors,(unsigned long long)rttMaxUs,(unsigned long)fwRequests,(unsigned long)fwResponses,(unsigned long)valuesRequests,(unsigned long)valuesResponses,(unsigned long)uartBytes,logger.stateName(),s.runName,(unsigned long)s.queueUsed,(unsigned long)s.queueHighWater,(unsigned long)s.dropped,(unsigned long)s.writeErrors,summaryPending?"false":"true",s.fault);
  web.send(200,"application/json",json);
}
const char page[]=R"HTML(<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:15px system-ui;background:#10151c;color:#e7edf3;margin:12px}.c{background:#1b2430;padding:10px;margin:8px 0;border-radius:8px;white-space:pre-wrap}button{padding:10px;margin:3px;min-width:96px}.danger{background:#b53232;color:white}</style><h2>XIAO VESC duty pulse test</h2><div class="c" id="s">loading</div><div class="c"><button onclick="post('/api/log/start')">Start log</button><button onclick="post('/api/log/stop')">Stop log</button><button onclick="post('/api/motor/arm')">ARM 10 s</button><button onclick="post('/api/motor/pulse')">3 % / 1.0 s</button><button class="danger" onclick="post('/api/motor/estop')">E-STOP</button><span id="m">Ready</span></div><div class="c" id="d"></div><div class="c">No duty command at boot. Start log, confirm values and fault=0, ARM, then Pulse. The pulse is fixed positive 3% for 1.0 second and duty=0 is sent at the end.</div><script>let busy=false;async function post(x){if(busy)return;busy=true;document.getElementById('m').textContent='sending...';try{let r=await fetch(x,{method:'POST',cache:'no-store'});if(!r.ok)throw Error(await r.text());document.getElementById('m').textContent='accepted'}catch(e){document.getElementById('m').textContent='error: '+e.message}finally{busy=false;u()}}function n(x,u){return x===null?'--':x+u}async function u(){try{let j=await(await fetch('/api/latest',{cache:'no-store'})).json();document.getElementById('s').textContent='Stage '+j.stage+' | '+(j.vesc_detected?'VESC DETECTED':'VESC WAITING')+' | SD '+j.sd+' '+j.run+' queue '+j.queue+'/'+j.qmax+' drop '+j.drops+' SDerr '+j.sd_errors;document.getElementById('d').textContent='FW '+j.fw+' HW '+j.hardware+' | VALUES '+(j.values_valid?'VALID':'WAITING')+' age '+n(j.values_age_ms,'ms')+'\nERPM '+n(j.erpm,'')+' | current '+n(j.motor_current_a,' A')+' | input '+n(j.input_voltage_v,' V')+' | fault '+j.fault+'\nDUTY TEST armed='+j.control_armed+' active='+j.pulse_active+' fixed='+j.pulse_duty+' / '+j.pulse_duration_ms+' ms | pulses '+j.pulse_count+' estops '+j.estop_count+'\nCRC '+j.crc_errors+' timeout '+j.timeouts+' parse '+j.parse_errors+' | RTT max '+j.rtt_max_us+' us'}catch(e){document.getElementById('s').textContent='web error: '+e.message}}setInterval(u,250);u()</script>)HTML";
void startLog(){if(logger.state()!=vlog::State::Ready){web.send(409,"application/json","{\"error\":\"logger is not ready\"}");return;}sessionArmed=false;summaryPending=false;logger.requestStart();web.send(202,"application/json","{\"requested\":\"start\"}");}void stopLog(){if(pulseActive)emergencyStop();summaryPending=true;logger.requestStop();web.send(202,"application/json","{\"requested\":\"stop\"}");}void webBegin(){WiFi.persistent(false);WiFi.mode(WIFI_AP);WiFi.softAP(kApSsid,kApPassword);web.on("/",HTTP_GET,[]{web.send(200,"text/html; charset=utf-8",page);});web.on("/api/latest",HTTP_GET,api);web.on("/api/log/start",HTTP_POST,startLog);web.on("/api/log/stop",HTTP_POST,stopLog);web.on("/api/motor/arm",HTTP_POST,armPulse);web.on("/api/motor/pulse",HTTP_POST,pulseMotor);web.on("/api/motor/estop",HTTP_POST,estopMotor);web.on("/favicon.ico",HTTP_GET,[]{web.send(204);});web.begin();}
void writeSummary(){if(!summaryPending||logger.isLogging()||logger.state()!=vlog::State::Ready||millis()-summaryTryMs<500)return;summaryTryMs=millis();const auto&s=logger.stats();char t[1400];snprintf(t,sizeof(t),"firmware=%s %s\nboard=%s\nstage=2-duty-confirm\nVESC_UART_TX_GPIO=%d\nVESC_UART_RX_GPIO=%d\nUART_baud=%lu\nvesc_detected=%d\nfw_major=%u\nfw_minor=%u\nhardware_name=%s\nfirmware_name=%s\nfw_requests_during_log=%lu\nfw_responses_during_log=%lu\nvalues_requests=%lu\nvalues_responses=%lu\nvalues_valid=%d\ncrc_errors=%lu\nframing_errors=%lu\ninvalid_length=%lu\nparse_errors=%lu\nunexpected_command=%lu\nuart_overflow=0\nraw_log_drop=%lu\nparsed_log_drop=%lu\nsd_write_errors=%lu\nqueue_high_water=%lu\nround_trip_avg_us=%llu\nround_trip_max_us=%llu\nnormal_stop=1\n",kFirmwareName,kFirmwareVersion,kBoardName,kVescUartTxPin,kVescUartRxPin,(unsigned long)kVescUartBaud,fw.valid,fw.major,fw.minor,fw.valid?fw.hardwareName:"not received",fw.valid?fw.firmwareName:"not received",(unsigned long)fwRequests,(unsigned long)fwResponses,(unsigned long)valuesRequests,(unsigned long)valuesResponses,values.valid,(unsigned long)crcErrors,(unsigned long)framingErrors,(unsigned long)lengthErrors,(unsigned long)parseErrors,(unsigned long)unexpected,(unsigned long)rawDrops,(unsigned long)parsedDrops,(unsigned long)s.writeErrors,(unsigned long)s.queueHighWater,(unsigned long long)((fwResponses+valuesResponses)?rttSumUs/(fwResponses+valuesResponses):0),(unsigned long long)rttMaxUs);if(logger.writeSummary(t))summaryPending=false;}
}
void setup(){Serial.begin(115200);delay(300);bootUs=esp_timer_get_time();vescUart.begin(kVescUartBaud,SERIAL_8N1,kVescUartRxPin,kVescUartTxPin);logger.begin();webBegin();Serial.printf("%s %s Stage2 duty confirmation: guarded 3 percent 1 second pulse; values 50 Hz during pulse; AP=%s http://%s/\n",kFirmwareName,kFirmwareVersion,kApSsid,WiFi.softAPIP().toString().c_str());}
void loop(){drainUart();logger.service();serviceStage1B();servicePulse();systemLog();web.handleClient();logger.service();writeSummary();if(millis()-lastSerialMs>=kSerialStatusIntervalMs){lastSerialMs=millis();const auto&s=logger.stats();Serial.printf("vesc_detected=%d fw=%u.%u hz=0 age_ms=%llu timeout=%lu crc=%lu framing=%lu parse=%lu rtt_avg_us=%llu rtt_max_us=%llu SD=%s q=%lu/%lu drop=%lu SDerr=%lu heap=%lu stage=2-duty-confirm values_TX=enabled\n",fw.valid,fw.major,fw.minor,(unsigned long long)(lastResponseUs?(esp_timer_get_time()-lastResponseUs)/1000:UINT32_MAX),(unsigned long)timeouts,(unsigned long)crcErrors,(unsigned long)framingErrors,(unsigned long)parseErrors,(unsigned long long)(fwResponses?rttSumUs/fwResponses:0),(unsigned long long)rttMaxUs,logger.stateName(),(unsigned long)s.queueUsed,(unsigned long)s.queueHighWater,(unsigned long)s.dropped,(unsigned long)s.writeErrors,(unsigned long)ESP.getFreeHeap());}delay(1);}