#include "bno_reader.h"
#include "app_config.h"
#include <esp_timer.h>
#include <math.h>
using namespace app_config;
namespace bno { namespace { uint64_t nowUs(){return (uint64_t)esp_timer_get_time();} void euler(Latest&x){float n=sqrtf(x.qx*x.qx+x.qy*x.qy+x.qz*x.qz+x.qw*x.qw);if(n<1e-6f)return;float qx=x.qx/n,qy=x.qy/n,qz=x.qz/n,qw=x.qw/n;x.roll=atan2f(2*(qw*qx+qy*qz),1-2*(qx*qx+qy*qy))*180.0f/M_PI;float p=fmaxf(-1.0f,fminf(1.0f,2*(qw*qy-qz*qx)));x.pitch=asinf(p)*180.0f/M_PI;x.yaw=atan2f(2*(qw*qz+qx*qy),1-2*(qy*qy+qz*qz))*180.0f/M_PI;} }
void Rate::add(uint64_t t,uint8_t s){if(count){uint64_t d=t-previousUs;if(d>maxGapUs)maxGapUs=d;missing+=(uint8_t)(s-previousSequence-1);}else firstUs=t;previousUs=lastUs=t;previousSequence=s;count++;}
void Reader::setFault(const char*s){snprintf(fault_,sizeof(fault_),"%s",s);} bool Reader::enableReports(){return sensor_.enableReport(SH2_GAME_ROTATION_VECTOR,kRotationIntervalUs)&&sensor_.enableReport(SH2_GYROSCOPE_CALIBRATED,kAccelGyroIntervalUs)&&sensor_.enableReport(SH2_ACCELEROMETER,kAccelGyroIntervalUs);}
bool Reader::init(){ready_=false;address_=0;Wire.begin(kBnoSdaPin,kBnoSclPin);Wire.setClock(kBnoI2cHz);uint8_t a=0;for(uint8_t i=0x08;i<0x78;i++){Wire.beginTransmission(i);if(!Wire.endTransmission()&&(i==kBnoAddress||i==kBnoAlternateAddress)){a=i;break;}}if(!a){setFault("BNO08X not detected (0x4A/0x4B)");return false;}if(!sensor_.begin_I2C(a,&Wire)){setFault("begin_I2C failed");return false;}if(!enableReports()){setFault("enableReport failed");return false;}address_=a;ready_=true;latest_.lastUs=nowUs();setFault("none");return true;}
bool Reader::begin(){pinMode(kBnoRstPin,OUTPUT);digitalWrite(kBnoRstPin,HIGH);pinMode(kBnoIntPin,INPUT_PULLUP);return init();}
void Reader::handle(const sh2_SensorValue_t&e,void(*out)(const Sample&)){Sample s{};s.accuracy=e.status&3;s.sequence=e.sequence;s.rxUs=nowUs();s.sensorUs=e.timestamp;if(e.sensorId==SH2_ACCELEROMETER){s.type=EventType::Accel;s.v[0]=e.un.accelerometer.x;s.v[1]=e.un.accelerometer.y;s.v[2]=e.un.accelerometer.z;latest_.ax=s.v[0];latest_.ay=s.v[1];latest_.az=s.v[2];latest_.accelValid=true;latest_.accelUs=s.rxUs;accelRate_.add(s.rxUs,s.sequence);}else if(e.sensorId==SH2_GYROSCOPE_CALIBRATED){s.type=EventType::Gyro;s.v[0]=e.un.gyroscope.x;s.v[1]=e.un.gyroscope.y;s.v[2]=e.un.gyroscope.z;latest_.gx=s.v[0];latest_.gy=s.v[1];latest_.gz=s.v[2];latest_.gyroValid=true;latest_.gyroUs=s.rxUs;gyroRate_.add(s.rxUs,s.sequence);}else if(e.sensorId==SH2_GAME_ROTATION_VECTOR){s.type=EventType::Rotation;s.v[0]=e.un.gameRotationVector.i;s.v[1]=e.un.gameRotationVector.j;s.v[2]=e.un.gameRotationVector.k;s.v[3]=e.un.gameRotationVector.real;latest_.qx=s.v[0];latest_.qy=s.v[1];latest_.qz=s.v[2];latest_.qw=s.v[3];euler(latest_);s.v[4]=latest_.roll;s.v[5]=latest_.pitch;s.v[6]=latest_.yaw;latest_.rotationValid=true;latest_.rotationUs=s.rxUs;rotationRate_.add(s.rxUs,s.sequence);}else return;latest_.lastUs=s.rxUs;out(s);}
void Reader::poll(void(*out)(const Sample&)){if(!ready_)return;if(sensor_.wasReset()&&!enableReports()){ready_=false;setFault("report re-enable failed");return;}for(uint8_t i=0;i<24;i++){if(!sensor_.getSensorEvent(&value_))break;handle(value_,out);}}
void Reader::recover(){uint32_t n=millis();if(ready_&&n-(uint32_t)(latest_.lastUs/1000)<=kNoDataTimeoutMs)return;if(n-lastReinitMs_<kReinitIntervalMs)return;lastReinitMs_=n;reinitCount_++;setFault(ready_?"BNO data timeout":"BNO init retry");init();} void Reader::resetRunStats(){accelRate_={};gyroRate_={};rotationRate_={};}
}