#include "sd_logger.h"
#include <SPI.h>
#include <Preferences.h>
#include <esp_timer.h>
#include <cstring>
using namespace app_config; namespace btf { namespace {constexpr uint32_t HM=0x42544648UL,RM=0x42544652UL;void u8(uint8_t*&p,uint8_t v){*p++=v;}void u16(uint8_t*&p,uint16_t v){u8(p,v);u8(p,v>>8);}void u32(uint8_t*&p,uint32_t v){for(int i=0;i<4;i++)u8(p,v>>(8*i));}void u64(uint8_t*&p,uint64_t v){for(int i=0;i<8;i++)u8(p,v>>(8*i));}}
void Logger::setFault(const char*s){snprintf(stats_.fault,sizeof(stats_.fault),"%s",s);}uint32_t Logger::crc(const uint8_t*d,size_t n)const{uint32_t c=0xffffffff;while(n--){c^=*d++;for(int i=0;i<8;i++)c=(c>>1)^((c&1)?0xedb88320:0);}return ~c;}const char* Logger::stateName()const{switch(state_){case State::NoCard:return "NO_CARD";case State::Ready:return "READY";case State::Logging:return "LOGGING";case State::Stopping:return "STOPPING";default:return "ERROR";}}
bool Logger::begin(){SPI.begin(kSdSckPin,kSdMisoPin,kSdMosiPin,kSdCsPin);if(!SD.begin(kSdCsPin,SPI,20000000)){state_=State::NoCard;setFault("SD mount failed/no card");return false;}if(!SD.exists(kLogDirectory)&&!SD.mkdir(kLogDirectory)){state_=State::Error;setFault("BNO_TOF mkdir failed");return false;}stats_.mounted=true;state_=State::Ready;setFault("none");xTaskCreatePinnedToCore(task,"btf_sd",8192,this,1,nullptr,0);return true;}void Logger::requestStart(){if(state_==State::Ready)start_=true;}void Logger::requestStop(){if(state_==State::Logging){Event e{};e.type=Type::LogEnd;e.rxUs=esp_timer_get_time();enqueue(e);stop_=true;}}
bool Logger::enqueue(const Event&e){if(!isLogging())return false;portENTER_CRITICAL(&mux_);if(count_>=kLogQueueCapacity){stats_.dropped++;portEXIT_CRITICAL(&mux_);return false;}q_[head_]=e;head_=(head_+1)%kLogQueueCapacity;count_++;stats_.queueUsed=count_;if(count_>stats_.queueHighWater)stats_.queueHighWater=count_;portEXIT_CRITICAL(&mux_);return true;}bool Logger::pop(Event&e){portENTER_CRITICAL(&mux_);if(!count_){portEXIT_CRITICAL(&mux_);return false;}e=q_[tail_];tail_=(tail_+1)%kLogQueueCapacity;count_--;stats_.queueUsed=count_;portEXIT_CRITICAL(&mux_);return true;}
void Logger::header(){uint8_t b[kHeaderBytes]{};uint8_t*p=b;u32(p,HM);u16(p,kLogFormatVersion);u16(p,kHeaderBytes);u16(p,kRecordBytes);u8(p,1);u8(p,0);u32(p,kBnoI2cHz);u32(p,kTofI2cHz);u32(p,kAccelGyroIntervalUs);u32(p,kRotationIntervalUs);u64(p,esp_timer_get_time());u8(p,kBnoAddress);u8(p,kBnoSdaPin);u8(p,kBnoSclPin);u8(p,kBnoIntPin);u8(p,kBnoRstPin);u8(p,kTofAddress);u8(p,kTofSdaPin);u8(p,kTofSclPin);u8(p,kSdCsPin);u8(p,kSdSckPin);u8(p,kSdMisoPin);u8(p,kSdMosiPin);snprintf((char*)p,72,"%s %s stage2_bno_tof",kFirmwareName,kFirmwareVersion);p=b+kHeaderBytes-4;u32(p,crc(b,kHeaderBytes-4));file_.write(b,sizeof(b));}
bool Logger::openRun(){Preferences n;n.begin("bnotof",false);uint32_t r=n.getUInt("next",1);for(uint16_t i=0;i<100;i++,r++){snprintf(stats_.runName,sizeof(stats_.runName),"RUN%04lu",(unsigned long)r);char path[32];snprintf(path,sizeof(path),"%s/%s.BIN",kLogDirectory,stats_.runName);if(!SD.exists(path)){file_=SD.open(path,FILE_WRITE);if(!file_){n.end();setFault("BIN create failed");return false;}n.putUInt("next",r+1);n.end();header();char t[32];snprintf(t,sizeof(t),"%s/%s.TXT",kLogDirectory,stats_.runName);SD.remove(t);File f=SD.open(t,FILE_WRITE);if(f){f.printf("firmware=%s %s\nstatus=recording_or_unfinished\n",kFirmwareName,kFirmwareVersion);f.close();}return true;}}n.end();setFault("RUN number exhausted");return false;}
void Logger::record(uint8_t*out,const Event&e,uint32_t seq){memset(out,0,kRecordBytes);uint8_t*p=out;u32(p,RM);u16(p,kLogFormatVersion);u8(p,(uint8_t)e.type);u8(p,e.accuracy);u16(p,kRecordBytes);u32(p,seq);u64(p,e.rxUs);u32(p,e.deltaUs);u64(p,e.sensorUs);u16(p,e.sequence);u16(p,e.sensorUs?1:0);memcpy(p,e.payload,kPayloadBytes);p=out+kRecordBytes-4;u32(p,crc(out,kRecordBytes-4));}
void Logger::task(void*x){static_cast<Logger*>(x)->writer();}void Logger::writer(){for(;;){if(state_==State::Logging||state_==State::Stopping){busy_=true;uint8_t block[kSdWriteBlockBytes];size_t used=0;Event e;uint32_t start=micros();while(used+kRecordBytes<=sizeof(block)&&pop(e)){record(block+used,e,++recordSequence_);used+=kRecordBytes;}if(used){size_t w=file_.write(block,used);if(w!=used){stats_.writeErrors++;state_=State::Error;setFault("SD block write failed");}else stats_.saved+=used/kRecordBytes;}uint32_t d=micros()-start;if(d>stats_.maxWriteUs)stats_.maxWriteUs=d;if(millis()-lastFlushMs_>=kSdFlushIntervalMs){file_.flush();lastFlushMs_=millis();}busy_=false;}vTaskDelay(1);}}
void Logger::service(){if(start_){start_=false;if(openRun()){head_=tail_=count_=0;recordSequence_=0;stats_.saved=stats_.dropped=stats_.writeErrors=stats_.queueHighWater=stats_.maxWriteUs=0;lastFlushMs_=millis();state_=State::Logging;}else state_=State::Error;}if(stop_){stop_=false;state_=State::Stopping;}if(state_==State::Stopping&&count_==0&&!busy_)closeRun();}void Logger::closeRun(){file_.flush();file_.close();state_=State::Ready;}bool Logger::writeSummary(const char*x){if(!stats_.mounted||!stats_.runName[0])return false;char p[32];snprintf(p,sizeof(p),"%s/%s.TXT",kLogDirectory,stats_.runName);SD.remove(p);File f=SD.open(p,FILE_WRITE);if(!f)return false;size_t n=strlen(x),w=f.write((const uint8_t*)x,n);f.flush();f.close();return w==n;}
}