#include "gnss_receiver.h"
#include <cstring>
#include <cstdlib>
#include <cmath>
namespace gnss {
void Receiver::begin(HardwareSerial& serial){serial.setRxBufferSize(app_config::kGnssUartRxBufferBytes);serial.begin(app_config::kGnssBaud,SERIAL_8N1,app_config::kGnssRxPin,app_config::kGnssTxPin);}
void Receiver::count(uint32_t Counts::*field){total_.*field+=1;window_.*field+=1;}
bool Receiver::number(const char*s,double&v){if(!s||!*s)return false;char*e=nullptr;v=strtod(s,&e);return e&&e!=s&&*e=='\0'&&std::isfinite(v);}
bool Receiver::coord(const char*s,const char*hem,bool lat,double&v){double x;if(!number(s,x)||!hem||!*hem)return false;double d=floor(x/100.0);v=d+(x-d*100.0)/60.0;if((lat&&(*hem=='S'||*hem=='s'))||(!lat&&(*hem=='W'||*hem=='w')))v=-v;return (lat?fabs(v)<=90.0:fabs(v)<=180.0);}
void Receiver::typeOf(const char*s,char*out){out[0]=0;if(!s||s[0]!='$')return;const char*comma=strchr(s,',');size_t n=comma?(size_t)(comma-s-1):strlen(s+1);if(n>=3){const char*p=s+1+n-3;snprintf(out,7,"%c%c%c",p[0],p[1],p[2]);}}
bool Receiver::checksum(const char*s){if(!s||s[0]!='$')return false;const char*star=strrchr(s,'*');if(!star||star[1]==0||star[2]==0||star[3]!=0)return false;uint8_t c=0;for(const char*p=s+1;p<star;p++)c^=(uint8_t)*p;char h[3]={star[1],star[2],0};char*e=nullptr;long claimed=strtol(h,&e,16);return e&&*e==0&&claimed==c;}
bool Receiver::feed(char c,uint64_t now,Sentence&out){count(&Counts::bytes);if(c=='$'){collecting_=true;overlong_=false;len_=0;line_[len_++]=c;startedUs_=now;return false;}if(!collecting_)return false;if(c=='\r')return false;if(c=='\n'){collecting_=false;return finish(now,out);}if(len_<app_config::kGnssInputLineChars){line_[len_++]=c;}else overlong_=true;return false;}
void Receiver::expire(uint64_t now){if(collecting_&&now-startedUs_>(uint64_t)app_config::kGnssSentenceTimeoutMs*1000ULL){collecting_=false;len_=0;overlong_=false;count(&Counts::unfinished);}}
bool Receiver::finish(uint64_t now,Sentence&out){line_[len_]=0;out=Sentence{};out.endUs=now;out.truncated=overlong_||len_>app_config::kGnssMaxSentenceChars;size_t take=len_;if(take>app_config::kGnssMaxSentenceChars)take=app_config::kGnssMaxSentenceChars;memcpy(out.raw,line_,take);out.raw[take]=0;out.rawLength=(uint8_t)take;typeOf(line_,out.type);snprintf(latest_.lastType,sizeof(latest_.lastType),"%s",out.type);latest_.lastSentenceEndUs=now;count(&Counts::sentences);if(out.truncated){count(&Counts::overlong);return true;}out.checksumValid=checksum(line_);if(!out.checksumValid){count(&Counts::checksumErrors);return true;}count(&Counts::validSentences);out.parsed=parse(line_,now,out);return true;}
bool Receiver::parse(char*line,uint64_t now,Sentence&out){char*star=strrchr(line,'*');if(!star){count(&Counts::parseErrors);return false;}*star=0;char*fields[24]{};uint8_t n=0;char*p=line+1;fields[n++]=p;for(;*p&&n<24;p++)if(*p==','){*p=0;fields[n++]=p+1;}char typ[7];typeOf(line,typ);bool known=!strcmp(typ,"RMC")||!strcmp(typ,"GGA")||!strcmp(typ,"GSA")||!strcmp(typ,"VTG")||!strcmp(typ,"ZDA");bool parsed=false;double d=0;
if(!strcmp(typ,"RMC")){if(n<10){count(&Counts::parseErrors);return false;}if(number(fields[1],d)){snprintf(latest_.utcTime,sizeof(latest_.utcTime),"%s",fields[1]);latest_.flags|=UtcTimeValid;}if(number(fields[3],d)&&coord(fields[3],fields[4],true,latest_.latitude)){latest_.flags|=LatitudeValid;}if(number(fields[5],d)&&coord(fields[5],fields[6],false,latest_.longitude)){latest_.flags|=LongitudeValid;}if(number(fields[7],d)){latest_.speedMps=(float)(d*0.514444444);latest_.flags|=SpeedValid;}if(number(fields[8],d)){latest_.courseDeg=(float)d;latest_.flags|=CourseValid;}if(fields[9][0]){snprintf(latest_.utcDate,sizeof(latest_.utcDate),"%s",fields[9]);latest_.flags|=UtcDateValid;}if(fields[2][0]=='A')latest_.flags|=FixValid;else latest_.flags&=~FixValid;parsed=true;}
else if(!strcmp(typ,"GGA")){if(n<10){count(&Counts::parseErrors);return false;}if(fields[1][0]){snprintf(latest_.utcTime,sizeof(latest_.utcTime),"%s",fields[1]);latest_.flags|=UtcTimeValid;}if(coord(fields[2],fields[3],true,latest_.latitude))latest_.flags|=LatitudeValid;if(coord(fields[4],fields[5],false,latest_.longitude))latest_.flags|=LongitudeValid;if(number(fields[6],d)){latest_.fixType=(uint8_t)d;latest_.flags|=FixTypeValid;if(latest_.fixType)latest_.flags|=FixValid;else latest_.flags&=~FixValid;}if(number(fields[7],d)){latest_.satellites=(uint8_t)d;latest_.flags|=SatellitesValid;}if(number(fields[8],d)){latest_.hdop=(float)d;latest_.flags|=HdopValid;}if(number(fields[9],d)){latest_.altitudeM=(float)d;latest_.flags|=AltitudeValid;}parsed=true;}
else if(!strcmp(typ,"GSA")){if(n<3){count(&Counts::parseErrors);return false;}if(n>15&&number(fields[15],d)){latest_.pdop=(float)d;latest_.flags|=PdopValid;}if(n>16&&number(fields[16],d)){latest_.hdop=(float)d;latest_.flags|=HdopValid;}if(n>17&&number(fields[17],d)){latest_.vdop=(float)d;latest_.flags|=VdopValid;}parsed=true;}
else if(!strcmp(typ,"VTG")){if(n>1&&number(fields[1],d)){latest_.courseDeg=(float)d;latest_.flags|=CourseValid;}if(n>5&&number(fields[5],d)){latest_.speedMps=(float)(d*0.514444444);latest_.flags|=SpeedValid;}else if(n>7&&number(fields[7],d)){latest_.speedMps=(float)(d/3.6);latest_.flags|=SpeedValid;}parsed=true;}
else if(!strcmp(typ,"ZDA")){if(n>4){if(fields[1][0]){snprintf(latest_.utcTime,sizeof(latest_.utcTime),"%s",fields[1]);latest_.flags|=UtcTimeValid;}snprintf(latest_.utcDate,sizeof(latest_.utcDate),"%s%s%s",fields[2],fields[3],fields[4]);latest_.flags|=UtcDateValid;parsed=true;}}
if(known&&!parsed){count(&Counts::parseErrors);return false;}if(parsed){latest_.lastParseUs=now;out.parseUs=now;if(latest_.flags&FixValid)latest_.lastValidFixUs=now;}return parsed;}
Counts Receiver::takeWindow(){Counts x=window_;window_=Counts{};return x;}void Receiver::noteLogDrop(){count(&Counts::logDrops);}bool Receiver::receiving(uint64_t now)const{return latest_.lastSentenceEndUs&&now-latest_.lastSentenceEndUs<(uint64_t)app_config::kGnssNoDataTimeoutMs*1000ULL;}void Receiver::resetRunStats(){total_=Counts{};window_=Counts{};}
}