#include <Arduino.h>
#include <Wire.h>
#include <WiFi.h>
#include <WebServer.h>
#include <Adafruit_BNO08x.h>
#include <esp_timer.h>
#include <math.h>
#include "app_config.h"
#include "sd_logger.h"
#include "gnss_receiver.h"
using namespace app_config;
namespace {
Adafruit_BNO08x bno08x(kUseHardwareReset?kBnoRstPin:-1); WebServer web(kHttpPort); HardwareSerial gnssUart(1); gnss::Receiver gnssRx; sh2_SensorValue_t sv{}; bnolog::Logger logger;
struct Latest{bool a=false,g=false,q=false;float ax=0,ay=0,az=0,gx=0,gy=0,gz=0,qi=0,qj=0,qk=0,qw=1,roll=0,pitch=0,yaw=0;uint32_t am=0,gm=0,qm=0,last=0;} latest;
struct Rate{uint32_t n=0,missing=0;uint8_t prevSeq=0;uint64_t first=0,last=0,prev=0,sum=0,min=UINT64_MAX,max=0;void add(uint64_t t,uint8_t s){if(n){uint64_t d=t-prev;sum+=d;if(d<min)min=d;if(d>max)max=d;missing+=(uint8_t)(s-prevSeq-1);}else first=t;prevSeq=s;prev=last=t;n++;}float hz()const{return n>1?1000000.0f*(n-1)/(last-first):0;}} rateA,rateG,rateQ;
struct CallStats{uint32_t calls=0,success=0,empty=0,slow10=0,slow50=0,minUs=UINT32_MAX,maxUs=0;uint64_t sumUs=0;void add(uint32_t d,bool ok){calls++;sumUs+=d;if(d<minUs)minUs=d;if(d>maxUs)maxUs=d;if(ok)success++;else empty++;if(d>=10000)slow10++;if(d>=50000)slow50++;}} callStats;
volatile uint32_t intRise=0,intFall=0,intLastEdgeUs=0;volatile uint8_t intLevel=HIGH;portMUX_TYPE intMux=portMUX_INITIALIZER_UNLOCKED;
bool initialized=false,summaryPending=false;uint8_t addr=0;uint32_t reinit=0,runReinitBase=0,lastReinit=0,lastStatus=0,lastSystem=0,lastGnssStatus=0,lastSummaryAttempt=0;uint64_t lastGnssFixLogUs=0;gnss::Counts gnssWindow{};char fault[64]="none";
constexpr char page[]=R"HTML(<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><style>body{font:15px system-ui;background:#10151c;color:#e7edf3;margin:12px}.c{background:#1b2430;border-radius:8px;padding:10px;margin:8px 0}button{padding:10px;margin:3px}canvas{width:100%;height:130px;background:#090d12}</style><h2>BNO08X + GNSS + microSD logger</h2><div class=c id=s>loading</div><div class=c><button onclick="cmd('start')">Start log</button><button onclick="cmd('stop')">Stop log</button></div><div class=c id=g>GNSS loading</div><div class=c id=d>BNO loading</div><canvas id=c></canvas><script>let h=[];async function cmd(x){await fetch('/api/log/'+x,{method:'POST'})}function gr(){let x=c,w=x.width=x.clientWidth*devicePixelRatio,H=x.height=x.clientHeight*devicePixelRatio,z=x.getContext('2d');z.clearRect(0,0,w,H);let m=Math.max(1,...h.map(Math.abs));z.strokeStyle='#76e38c';z.beginPath();h.forEach((v,i)=>{let X=i*w/159,Y=H/2-v/m*H*.42;i?z.lineTo(X,Y):z.moveTo(X,Y)});z.stroke()}async function t(){try{let j=await(await fetch('/api/latest',{cache:'no-store'})).json();s.textContent=`BNO ${j.bno} SD ${j.sd_state} ${j.run} queue ${j.queue}/${j.qmax} drop ${j.drop} SDerr ${j.sd_error} I2C ${j.i2c_hz}Hz`;g.textContent=`GNSS ${j.gnss_receiving?'RX':'NO RX'} ${j.gnss_baud}bps ${j.gnss_bytes_s}B/s NMEA ${j.gnss_sentences_s}/s good ${j.gnss_valid_s}/s csumErr ${j.gnss_checksum_errors} parseErr ${j.gnss_parse_errors} fix ${j.gnss_fix} age ${j.gnss_age_ms}ms lat ${j.gnss_lat_valid?j.gnss_lat.toFixed(7):'--'} lon ${j.gnss_lon_valid?j.gnss_lon.toFixed(7):'--'} alt ${j.gnss_alt_valid?j.gnss_alt.toFixed(1):'--'}m speed ${j.gnss_speed_valid?j.gnss_speed.toFixed(2):'--'}m/s course ${j.gnss_course_valid?j.gnss_course.toFixed(1):'--'} sat ${j.gnss_sats_valid?j.gnss_sats:'--'} hdop ${j.gnss_hdop_valid?j.gnss_hdop.toFixed(2):'--'} logDrop ${j.gnss_log_drops}`;d.textContent=`Accel ${j.ax.toFixed(3)},${j.ay.toFixed(3)},${j.az.toFixed(3)} m/s2 | Gyro ${j.gx.toFixed(3)},${j.gy.toFixed(3)},${j.gz.toFixed(3)} rad/s | Hz A/G/Q ${j.ahz.toFixed(1)}/${j.ghz.toFixed(1)}/${j.qhz.toFixed(1)}`;h.push(j.az);if(h.length>160)h.shift();gr()}catch(e){s.textContent='web error'}}setInterval(t,500);t()</script>)HTML";
void setFault(const char*s){snprintf(fault,sizeof(fault),"%s",s);}uint64_t nowUs(){return (uint64_t)esp_timer_get_time();}
void IRAM_ATTR observeInt(){uint8_t l=digitalRead(kBnoIntPin);portENTER_CRITICAL_ISR(&intMux);if(l!=intLevel){if(l==LOW)intFall++;else intRise++;intLevel=l;intLastEdgeUs=micros();}portEXIT_CRITICAL_ISR(&intMux);}
void put16(uint8_t*&p,uint16_t v){*p++=v;*p++=v>>8;}void put32(uint8_t*&p,uint32_t v){for(int i=0;i<4;i++)*p++=v>>(8*i);}void put64(uint8_t*&p,uint64_t v){for(int i=0;i<8;i++)*p++=v>>(8*i);}void putF(uint8_t*&p,float v){memcpy(p,&v,4);p+=4;}void putD(uint8_t*&p,double v){memcpy(p,&v,8);p+=8;}
void quatEuler(){float n=sqrtf(latest.qi*latest.qi+latest.qj*latest.qj+latest.qk*latest.qk+latest.qw*latest.qw);if(n<1e-6f)return;float x=latest.qi/n,y=latest.qj/n,z=latest.qk/n,w=latest.qw/n;latest.roll=atan2f(2*(w*x+y*z),1-2*(x*x+y*y))*180/M_PI;float q=2*(w*y-z*x);q=fmaxf(-1,fminf(1,q));latest.pitch=asinf(q)*180/M_PI;latest.yaw=atan2f(2*(w*z+x*y),1-2*(y*y+z*z))*180/M_PI;}
void configure(){Wire.begin(kI2cSdaPin,kI2cSclPin);Wire.setClock(kI2cClockHz);}uint8_t scan(){for(uint8_t a=1;a<0x78;a++){Wire.beginTransmission(a);if(!Wire.endTransmission()&&(a==kAddressPrimary||a==kAddressAlternate))return a;}return 0;}bool reports(){return bno08x.enableReport(SH2_GAME_ROTATION_VECTOR,kRotationVectorReportIntervalUs)&&bno08x.enableReport(SH2_GYROSCOPE_CALIBRATED,kAccelGyroReportIntervalUs)&&bno08x.enableReport(SH2_ACCELEROMETER,kAccelGyroReportIntervalUs);}
bool init(const char*){initialized=false;addr=0;configure();uint8_t a=scan();if(!a){setFault("BNO08X not detected");return false;}if(!bno08x.begin_I2C(a,&Wire)){setFault("begin_I2C failed");return false;}if(!reports()){setFault("enableReport failed");return false;}addr=a;initialized=true;latest.last=millis();setFault("none");return true;}
void logBno(bnolog::RecordType t,uint8_t acc,uint8_t seq,uint64_t rx,uint64_t ts,const float*v,Rate&r){uint32_t delta=r.n?(uint32_t)(rx-r.prev):0;r.add(rx,seq);bnolog::Event e{};e.type=t;e.accuracy=acc;e.sensorSequence=seq;e.faultCode=strcmp(fault,"none")?1:0;e.rxUs=rx;e.deltaUs=delta;e.sensorUs=ts;e.sensorTimeValid=ts!=0;memcpy(e.payload,v,7*sizeof(float));logger.enqueue(e);}
void event(const sh2_SensorValue_t&e){uint64_t rx=nowUs();uint32_t m=millis();uint8_t ac=e.status&3;float v[7]={};if(e.sensorId==SH2_ACCELEROMETER){latest.ax=e.un.accelerometer.x;latest.ay=e.un.accelerometer.y;latest.az=e.un.accelerometer.z;latest.a=true;latest.am=m;v[0]=latest.ax;v[1]=latest.ay;v[2]=latest.az;logBno(bnolog::RecordType::Accel,ac,e.sequence,rx,e.timestamp,v,rateA);}else if(e.sensorId==SH2_GYROSCOPE_CALIBRATED){latest.gx=e.un.gyroscope.x;latest.gy=e.un.gyroscope.y;latest.gz=e.un.gyroscope.z;latest.g=true;latest.gm=m;v[0]=latest.gx;v[1]=latest.gy;v[2]=latest.gz;logBno(bnolog::RecordType::Gyro,ac,e.sequence,rx,e.timestamp,v,rateG);}else if(e.sensorId==SH2_GAME_ROTATION_VECTOR){latest.qi=e.un.gameRotationVector.i;latest.qj=e.un.gameRotationVector.j;latest.qk=e.un.gameRotationVector.k;latest.qw=e.un.gameRotationVector.real;quatEuler();latest.q=true;latest.qm=m;v[0]=latest.qi;v[1]=latest.qj;v[2]=latest.qk;v[3]=latest.qw;v[4]=latest.roll;v[5]=latest.pitch;v[6]=latest.yaw;logBno(bnolog::RecordType::Rotation,ac,e.sequence,rx,e.timestamp,v,rateQ);}else return;latest.last=m;}
void poll(){if(!initialized)return;if(bno08x.wasReset()&&!reports()){initialized=false;setFault("report re-enable failed");return;}for(int i=0;i<24;i++){uint64_t b=nowUs();bool ok=bno08x.getSensorEvent(&sv);uint32_t d=(uint32_t)(nowUs()-b);callStats.add(d,ok);if(d>=50000){bnolog::Event e{};e.type=bnolog::RecordType::I2cStall;e.rxUs=b;e.deltaUs=d;{uint8_t* p=e.payload;putF(p,(float)d);}logger.enqueue(e);}if(!ok)break;event(sv);}}
void recovery(){uint32_t n=millis();if(initialized&&n-latest.last<=kNoDataTimeoutMs)return;if(n-lastReinit<kReinitRetryIntervalMs)return;lastReinit=n;reinit++;setFault(initialized?"sensor timeout":"initialization retry");bool ok=init(fault);bnolog::Event e{};e.type=bnolog::RecordType::Reinit;e.rxUs=nowUs();{uint8_t* p=e.payload;putF(p,(float)reinit);putF(p,ok?1:0);}logger.enqueue(e);}
bool gnssPush(const bnolog::Event&e){if(!logger.isLogging())return false;if(logger.enqueue(e))return true;gnssRx.noteLogDrop();return false;}
void logGnssRaw(const gnss::Sentence&s){bnolog::Event e{};e.type=bnolog::RecordType::GnssRaw;e.rxUs=s.endUs;e.payload[0]=s.rawLength>108?108:s.rawLength;e.payload[1]=strlen(s.type);e.payload[2]=s.checksumValid;e.payload[3]=s.truncated||s.rawLength>108;memcpy(e.payload+4,s.type,6);memcpy(e.payload+10,s.raw,e.payload[0]);gnssPush(e);}
void logGnssFix(){const auto&l=gnssRx.latest();bnolog::Event e{};e.type=bnolog::RecordType::GnssFix;e.rxUs=l.lastSentenceEndUs;e.deltaUs=lastGnssFixLogUs?(uint32_t)(e.rxUs-lastGnssFixLogUs):0;lastGnssFixLogUs=e.rxUs;uint8_t*p=e.payload;put32(p,l.flags);snprintf((char*)p,12,"%s",l.utcTime);p+=12;snprintf((char*)p,8,"%s",l.utcDate);p+=8;*p++=l.fixType;*p++=(uint8_t)l.drState;*p++=l.satellites;*p++=0;putD(p,l.latitude);putD(p,l.longitude);putF(p,l.altitudeM);putF(p,l.speedMps);putF(p,l.courseDeg);putF(p,l.hdop);putF(p,l.pdop);putF(p,l.vdop);put32(p,(uint32_t)((nowUs()-l.lastSentenceEndUs)/1000));put64(p,l.lastParseUs);snprintf((char*)p,7,"%s",l.lastType);gnssPush(e);}
void gnssPoll(){for(uint16_t i=0;i<kGnssReadBudgetBytes&&gnssUart.available();i++){int x=gnssUart.read();if(x<0)break;gnss::Sentence s;if(gnssRx.feed((char)x,nowUs(),s)){logGnssRaw(s);if(s.parsed)logGnssFix();}}gnssRx.expire(nowUs());}
void gnssStatus(){uint32_t n=millis();if(n-lastGnssStatus<kGnssStatusIntervalMs)return;lastGnssStatus=n;gnssWindow=gnssRx.takeWindow();const auto&l=gnssRx.latest();bnolog::Event e{};e.type=bnolog::RecordType::GnssStatus;e.rxUs=nowUs();uint8_t*p=e.payload;put32(p,gnssWindow.bytes);put32(p,gnssWindow.sentences);put32(p,gnssWindow.validSentences);put32(p,gnssWindow.checksumErrors);put32(p,gnssWindow.parseErrors);put32(p,gnssWindow.overlong);put32(p,gnssWindow.logDrops);put32(p,l.lastSentenceEndUs?(uint32_t)((nowUs()-l.lastSentenceEndUs)/1000):UINT32_MAX);put32(p,l.lastValidFixUs?(uint32_t)((nowUs()-l.lastValidFixUs)/1000):UINT32_MAX);*p++=(l.flags&gnss::FixValid)?1:0;*p++=gnssRx.uartOverflowObservable()?1:0;gnssPush(e);Serial.printf("GNSS baud=%lu bytes/s=%lu nmea/s=%lu valid=%lu checksum_err=%lu parse_err=%lu fix=%d sats=%u hdop=%.2f lat=%.7f lon=%.7f speed=%.2f course=%.1f age_ms=%lu log_drops=%lu\n",(unsigned long)kGnssBaud,(unsigned long)gnssWindow.bytes,(unsigned long)gnssWindow.sentences,(unsigned long)gnssWindow.validSentences,(unsigned long)gnssWindow.checksumErrors,(unsigned long)gnssWindow.parseErrors,(l.flags&gnss::FixValid)?1:0,l.satellites,l.hdop,l.latitude,l.longitude,l.speedMps,l.courseDeg,(unsigned long)(l.lastSentenceEndUs?(nowUs()-l.lastSentenceEndUs)/1000:UINT32_MAX),(unsigned long)gnssRx.totals().logDrops);}
void systemRecord(){uint32_t n=millis();if(n-lastSystem<kSystemRecordIntervalMs)return;lastSystem=n;bnolog::Event e{};e.type=bnolog::RecordType::System;e.rxUs=nowUs();uint8_t*p=e.payload;put32(p,callStats.calls);put32(p,callStats.success);put32(p,callStats.empty);put32(p,callStats.maxUs);put32(p,callStats.slow10);put32(p,callStats.slow50);logger.enqueue(e);}
void resetRunStats(){rateA=Rate{};rateG=Rate{};rateQ=Rate{};callStats=CallStats{};gnssRx.resetRunStats();lastGnssFixLogUs=0;lastSystem=lastGnssStatus=millis();runReinitBase=reinit;}
void api(){auto&s=logger.stats();const auto&l=gnssRx.latest();uint64_t u=nowUs();char b[1800];snprintf(b,sizeof(b),"{\"bno\":\"%s\",\"addr\":\"0x%02X\",\"i2c_hz\":%lu,\"sd_state\":\"%s\",\"run\":\"%s\",\"queue\":%lu,\"qmax\":%u,\"drop\":%lu,\"sd_error\":%lu,\"ax\":%.5f,\"ay\":%.5f,\"az\":%.5f,\"gx\":%.5f,\"gy\":%.5f,\"gz\":%.5f,\"ahz\":%.2f,\"ghz\":%.2f,\"qhz\":%.2f,\"gnss_baud\":%lu,\"gnss_receiving\":%d,\"gnss_bytes_s\":%lu,\"gnss_sentences_s\":%lu,\"gnss_valid_s\":%lu,\"gnss_checksum_errors\":%lu,\"gnss_parse_errors\":%lu,\"gnss_log_drops\":%lu,\"gnss_fix\":%d,\"gnss_age_ms\":%lu,\"gnss_lat\":%.8f,\"gnss_lon\":%.8f,\"gnss_alt\":%.2f,\"gnss_speed\":%.3f,\"gnss_course\":%.2f,\"gnss_sats\":%u,\"gnss_hdop\":%.2f,\"gnss_lat_valid\":%d,\"gnss_lon_valid\":%d,\"gnss_alt_valid\":%d,\"gnss_speed_valid\":%d,\"gnss_course_valid\":%d,\"gnss_sats_valid\":%d,\"gnss_hdop_valid\":%d}",initialized?"RUNNING":"ERROR",addr,(unsigned long)kI2cClockHz,logger.stateName(),s.runName,(unsigned long)s.queueUsed,kLogQueueCapacity,(unsigned long)s.dropped,(unsigned long)s.writeErrors,latest.ax,latest.ay,latest.az,latest.gx,latest.gy,latest.gz,rateA.hz(),rateG.hz(),rateQ.hz(),(unsigned long)kGnssBaud,gnssRx.receiving(u)?1:0,(unsigned long)gnssWindow.bytes,(unsigned long)gnssWindow.sentences,(unsigned long)gnssWindow.validSentences,(unsigned long)gnssRx.totals().checksumErrors,(unsigned long)gnssRx.totals().parseErrors,(unsigned long)gnssRx.totals().logDrops,(l.flags&gnss::FixValid)?1:0,(unsigned long)(l.lastSentenceEndUs?(u-l.lastSentenceEndUs)/1000:UINT32_MAX),l.latitude,l.longitude,l.altitudeM,l.speedMps,l.courseDeg,l.satellites,l.hdop,(l.flags&gnss::LatitudeValid)?1:0,(l.flags&gnss::LongitudeValid)?1:0,(l.flags&gnss::AltitudeValid)?1:0,(l.flags&gnss::SpeedValid)?1:0,(l.flags&gnss::CourseValid)?1:0,(l.flags&gnss::SatellitesValid)?1:0,(l.flags&gnss::HdopValid)?1:0);web.send(200,"application/json",b);}
void start(){summaryPending=false;resetRunStats();logger.requestStart();web.send(202,"application/json","{\"requested\":\"start\"}");}void stop(){summaryPending=true;logger.requestStop();web.send(202,"application/json","{\"requested\":\"stop\"}");}
void webBegin(){WiFi.persistent(false);WiFi.mode(WIFI_AP);WiFi.softAP(kApSsid,kApPassword);web.on("/",HTTP_GET,[]{web.send(200,"text/html; charset=utf-8",page);});web.on("/api/latest",HTTP_GET,api);web.on("/api/log/start",HTTP_POST,start);web.on("/api/log/stop",HTTP_POST,stop);web.begin();}
void summary(){if(!summaryPending||logger.isLogging()||logger.state()!=bnolog::State::Ready||millis()-lastSummaryAttempt<1000)return;lastSummaryAttempt=millis();const auto&g=gnssRx.totals();const auto&l=gnssRx.latest();char t[1800];snprintf(t,sizeof(t),"firmware=%s %s\nbuild=%s %s\nboard=%s\ntest_setting=%s\nBNO08X=0x%02X SDA=%d SCL=%d INT=%d RST=%d I2C=%lu\nGNSS RX=%d TX=%d baud=%lu\nSD CS=%d SCK=%d MISO=%d MOSI=%d\naccel_count=%lu missing=%lu hz=%.3f\ngyro_count=%lu missing=%lu hz=%.3f\nrotation_count=%lu missing=%lu hz=%.3f\nget_event_calls=%lu success=%lu empty=%lu max_us=%lu slow50=%lu\ngnss_bytes=%lu sentences=%lu valid_sentences=%lu checksum_errors=%lu parse_errors=%lu overlong=%lu log_drops=%lu\ngnss_fix=%d sats=%u hdop=%.2f lat_valid=%d lon_valid=%d last_type=%s\nsaved=%lu drop=%lu sd_write_errors=%lu reinit=%lu fault=%s\nnormal_stop=1\n",kFirmwareName,kFirmwareVersion,__DATE__,__TIME__,kBoardName,kTestSettingName,addr,kI2cSdaPin,kI2cSclPin,kBnoIntPin,kBnoRstPin,(unsigned long)kI2cClockHz,kGnssRxPin,kGnssTxPin,(unsigned long)kGnssBaud,kSdCsPin,kSdSckPin,kSdMisoPin,kSdMosiPin,(unsigned long)rateA.n,(unsigned long)rateA.missing,rateA.hz(),(unsigned long)rateG.n,(unsigned long)rateG.missing,rateG.hz(),(unsigned long)rateQ.n,(unsigned long)rateQ.missing,rateQ.hz(),(unsigned long)callStats.calls,(unsigned long)callStats.success,(unsigned long)callStats.empty,(unsigned long)callStats.maxUs,(unsigned long)callStats.slow50,(unsigned long)g.bytes,(unsigned long)g.sentences,(unsigned long)g.validSentences,(unsigned long)g.checksumErrors,(unsigned long)g.parseErrors,(unsigned long)g.overlong,(unsigned long)g.logDrops,(l.flags&gnss::FixValid)?1:0,l.satellites,l.hdop,(l.flags&gnss::LatitudeValid)?1:0,(l.flags&gnss::LongitudeValid)?1:0,l.lastType,(unsigned long)logger.stats().saved,(unsigned long)logger.stats().dropped,(unsigned long)logger.stats().writeErrors,(unsigned long)(reinit-runReinitBase),fault);if(logger.writeSummary(t)){summaryPending=false;Serial.printf("TXT saved: /BNOLOG/%s.TXT\n",logger.stats().runName);}else Serial.printf("TXT retry: %s\n",logger.stats().fault);}
}
void setup(){Serial.begin(115200);delay(300);pinMode(kBnoRstPin,OUTPUT);digitalWrite(kBnoRstPin,HIGH);pinMode(kBnoIntPin,INPUT_PULLUP);intLevel=digitalRead(kBnoIntPin);attachInterrupt(digitalPinToInterrupt(kBnoIntPin),observeInt,CHANGE);gnssRx.begin(gnssUart);Serial.printf("%s v%s GNSS=%lu bps RX=%d TX=%d\n",kFirmwareName,kFirmwareVersion,(unsigned long)kGnssBaud,kGnssRxPin,kGnssTxPin);init("startup");logger.begin();webBegin();Serial.printf("AP %s http://%s/\n",kApSsid,WiFi.softAPIP().toString().c_str());}
void loop(){poll();recovery();gnssPoll();systemRecord();gnssStatus();logger.service();web.handleClient();logger.service();summary();if(millis()-lastStatus>=kStatusPrintIntervalMs){lastStatus=millis();Serial.printf("BNO=%d SD=%s A/G/Q=%.1f/%.1f/%.1f queue=%lu drop=%lu fault=%s\n",initialized,logger.stateName(),rateA.hz(),rateG.hz(),rateQ.hz(),(unsigned long)logger.stats().queueUsed,(unsigned long)logger.stats().dropped,fault);}delay(1);}