#include "sd_logger.h"
#include "app_config.h"
#include <SPI.h>
#include <Preferences.h>
#include <esp_timer.h>
#include <cstring>
using namespace app_config;
namespace bnolog {
namespace { constexpr uint32_t kHeaderMagic=0x424E4F48UL,kRecordMagic=0x424E4F52UL; void u8(uint8_t*&p,uint8_t v){*p++=v;} void u16(uint8_t*&p,uint16_t v){u8(p,v);u8(p,v>>8);} void u32(uint8_t*&p,uint32_t v){for(int i=0;i<4;i++)u8(p,v>>(8*i));} void u64(uint8_t*&p,uint64_t v){for(int i=0;i<8;i++)u8(p,v>>(8*i));} }
bool Logger::begin(){SPI.begin(kSdSckPin,kSdMisoPin,kSdMosiPin,kSdCsPin);if(!SD.begin(kSdCsPin,SPI,20000000)){setFault("SD mount failed/no card");state_=State::NoCard;return false;}if(!SD.exists(kLogDirectory)&&!SD.mkdir(kLogDirectory)){setFault("BNOLOG mkdir failed");state_=State::Error;return false;}stats_.mounted=true;stats_.cardType=SD.cardType();stats_.cardBytes=SD.cardSize();stats_.usedBytes=SD.usedBytes();state_=State::Ready;setFault("none");xTaskCreatePinnedToCore(writerEntry,"sd_writer",8192,this,1,nullptr,0);return true;}
void Logger::requestStart(){if(state_==State::Ready)startRequested_=true;} void Logger::requestStop(){if(state_==State::Logging)stopRequested_=true;} bool Logger::isLogging()const{return state_==State::Logging;} State Logger::state()const{return state_;} const Stats& Logger::stats()const{return stats_;}
const char* Logger::stateName()const{switch(state_){case State::NoCard:return "NO_CARD";case State::Ready:return "READY";case State::Logging:return "LOGGING";case State::Stopping:return "STOPPING";default:return "ERROR";}}
void Logger::setFault(const char*f){snprintf(stats_.fault,sizeof(stats_.fault),"%s",f);} uint32_t Logger::crc32(const uint8_t*d,size_t n)const{uint32_t c=0xFFFFFFFF;while(n--){c^=*d++;for(int i=0;i<8;i++)c=(c>>1)^((c&1)?0xEDB88320:0);}return ~c;}
bool Logger::openRun(){Preferences p;p.begin("bnolog",false);uint32_t run=p.getUInt("next",1);for(uint16_t i=0;i<100;i++,run++){snprintf(stats_.runName,sizeof(stats_.runName),"RUN%04lu",(unsigned long)run);char path[32];snprintf(path,sizeof(path),"%s/%s.BIN",kLogDirectory,stats_.runName);if(!SD.exists(path)){file_=SD.open(path,FILE_WRITE);if(!file_){setFault("BIN create failed");p.end();return false;}p.putUInt("next",run+1);p.end();writeHeader();char txtPath[32];snprintf(txtPath,sizeof(txtPath),"%s/%s.TXT",kLogDirectory,stats_.runName);File txt=SD.open(txtPath,FILE_WRITE);if(!txt){setFault("TXT create failed");}else{txt.printf("firmware=%s %s\nboard=%s\ntest_setting=%s\nstatus=recording_or_unfinished\n",kFirmwareName,kFirmwareVersion,kBoardName,kTestSettingName);txt.flush();txt.close();}return true;}}p.end();setFault("RUN number exhausted");return false;}
void Logger::writeHeader(){uint8_t b[kLogHeaderBytes]{};uint8_t*q=b;u32(q,kHeaderMagic);u16(q,kLogFormatVersion);u16(q,kLogHeaderBytes);u16(q,kLogRecordBytes);u8(q,1);u8(q,0);u32(q,kI2cClockHz);u32(q,kAccelGyroReportIntervalUs);u32(q,kAccelGyroReportIntervalUs);u32(q,kRotationVectorReportIntervalUs);u64(q,esp_timer_get_time());u8(q,kAddressPrimary);u8(q,kI2cSdaPin);u8(q,kI2cSclPin);u8(q,kBnoIntPin);u8(q,kBnoRstPin);u8(q,kSdCsPin);u8(q,kSdSckPin);u8(q,kSdMisoPin);u8(q,kSdMosiPin);u8(q,kGnssRxPin);u8(q,kGnssTxPin);u32(q,kGnssBaud);snprintf((char*)q,48,"%s %s %s",kFirmwareName,kFirmwareVersion,kTestSettingName);q+=48;snprintf((char*)q,48,"%s %s",kBoardName,__DATE__ " " __TIME__);uint8_t*z=b+kLogHeaderBytes-4;u32(z,crc32(b,kLogHeaderBytes-4));if(file_.write(b,sizeof(b))!=sizeof(b)){setFault("header write failed");state_=State::Error;}}
void Logger::serializeRecord(uint8_t*out,const Event&e,uint32_t seq){memset(out,0,kLogRecordBytes);uint8_t*p=out;u32(p,kRecordMagic);u16(p,kLogFormatVersion);u8(p,(uint8_t)e.type);u8(p,e.accuracy&3);u16(p,kLogRecordBytes);u32(p,seq);u64(p,e.rxUs);u32(p,e.deltaUs);u64(p,e.sensorUs);u16(p,e.faultCode);u16(p,(e.sensorTimeValid?1:0)|((uint16_t)e.sensorSequence<<8));memcpy(p,e.payload,kPayloadBytes);p+=kPayloadBytes;uint8_t*z=out+kLogRecordBytes-4;u32(z,crc32(out,kLogRecordBytes-4));}
bool Logger::enqueue(const Event&e){if(!isLogging())return false;portENTER_CRITICAL(&mux_);if(count_>=kLogQueueCapacity){stats_.dropped++;portEXIT_CRITICAL(&mux_);return false;}queue_[head_]=e;head_=(head_+1)%kLogQueueCapacity;count_++;stats_.queueUsed=count_;if(count_>stats_.queueHighWater)stats_.queueHighWater=count_;portEXIT_CRITICAL(&mux_);return true;}
bool Logger::pop(Event&e){portENTER_CRITICAL(&mux_);if(!count_){portEXIT_CRITICAL(&mux_);return false;}e=queue_[tail_];tail_=(tail_+1)%kLogQueueCapacity;count_--;stats_.queueUsed=count_;portEXIT_CRITICAL(&mux_);return true;}
void Logger::writerEntry(void*p){static_cast<Logger*>(p)->writerLoop();} void Logger::writerLoop(){for(;;){if(state_==State::Logging||state_==State::Stopping){writerBusy_=true;uint8_t block[kSdWriteBlockBytes];size_t used=0;uint16_t n=0;Event e;uint32_t start=micros();while(used+kLogRecordBytes<=sizeof(block)&&pop(e)){serializeRecord(block+used,e,++sequence_);used+=kLogRecordBytes;n++;}if(used){size_t w=file_.write(block,used);if(w!=used){stats_.writeErrors++;setFault("SD block write failed");state_=State::Error;}else stats_.saved+=n;}uint32_t d=micros()-start;if(d>stats_.maxWriteUs)stats_.maxWriteUs=d;if(millis()-lastFlushMs_>=kSdFlushIntervalMs){file_.flush();lastFlushMs_=millis();stats_.lastFlushMs=lastFlushMs_;}writerBusy_=false;}vTaskDelay(1);}}
void Logger::service(){if(startRequested_){startRequested_=false;if(openRun()){head_=tail_=count_=0;sequence_=0;stats_.saved=stats_.dropped=stats_.writeErrors=stats_.queueHighWater=0;lastFlushMs_=millis();state_=State::Logging;}else state_=State::Error;}if(stopRequested_){stopRequested_=false;state_=State::Stopping;}if(state_==State::Stopping&&count_==0&&!writerBusy_)closeRun();}
void Logger::closeRun(){if(file_){file_.flush();file_.close();}stats_.usedBytes=SD.usedBytes();state_=State::Ready;}
bool Logger::writeSummary(const char*text){if(!stats_.mounted||!stats_.runName[0]){setFault("TXT unavailable");return false;}char pth[32];snprintf(pth,sizeof(pth),"%s/%s.TXT",kLogDirectory,stats_.runName);File f=SD.open(pth,FILE_WRITE);if(!f){setFault("TXT open failed");return false;}size_t n=strlen(text),w=f.write((const uint8_t*)text,n);f.flush();f.close();if(w!=n){setFault("TXT short write");return false;}setFault("none");return true;}
}