#include "sd_logger.h"
#include <SPI.h>
#include <Preferences.h>
#include <esp_timer.h>
#include <cstring>
using namespace cfg; namespace vlog { namespace {constexpr uint32_t HM=0x494C4F47UL,RM=0x49524344UL; void u8(uint8_t*&p,uint8_t v){*p++=v;}void u16(uint8_t*&p,uint16_t v){u8(p,v>>8);u8(p,v);}void u32(uint8_t*&p,uint32_t v){for(int i=3;i>=0;i--)u8(p,v>>(i*8));}void u64(uint8_t*&p,uint64_t v){for(int i=7;i>=0;i--)u8(p,v>>(i*8));}}
void Logger::setFault(const char*s){snprintf(stats_.fault,sizeof(stats_.fault),"%s",s);}uint32_t Logger::crc(const uint8_t*d,size_t n)const{uint32_t c=0xffffffff;while(n--){c^=*d++;for(int i=0;i<8;i++)c=(c>>1)^((c&1)?0xedb88320:0);}return ~c;}const char*Logger::stateName()const{switch(state_){case State::NoCard:return "NO_CARD";case State::Ready:return "READY";case State::Logging:return "LOGGING";case State::Stopping:return "STOPPING";default:return "ERROR";}}
bool Logger::begin(){SPI.begin(kSdSckPin,kSdMisoPin,kSdMosiPin,kSdCsPin);if(!SD.begin(kSdCsPin,SPI,20000000)){state_=State::NoCard;setFault("SD mount failed/no card");return false;}if(!SD.exists(kLogDirectory)&&!SD.mkdir(kLogDirectory)){state_=State::Error;setFault("INALOG mkdir failed");return false;}stats_.mounted=true;state_=State::Ready;setFault("none");xTaskCreatePinnedToCore(task,"ina_sd",8192,this,1,nullptr,0);return true;}
bool Logger::enqueue(const Event&e){if(!isLogging())return false;portENTER_CRITICAL(&mux_);if(count_>=kLogQueueCapacity){stats_.dropped++;portEXIT_CRITICAL(&mux_);return false;}q_[head_]=e;head_=(head_+1)%kLogQueueCapacity;count_++;stats_.queueUsed=count_;if(count_>stats_.queueHighWater)stats_.queueHighWater=count_;portEXIT_CRITICAL(&mux_);return true;}bool Logger::pop(Event&e){portENTER_CRITICAL(&mux_);if(!count_){portEXIT_CRITICAL(&mux_);return false;}e=q_[tail_];tail_=(tail_+1)%kLogQueueCapacity;count_--;stats_.queueUsed=count_;portEXIT_CRITICAL(&mux_);return true;}
void Logger::header(){uint8_t b[kHeaderBytes]{};uint8_t*p=b;u32(p,HM);u16(p,kLogFormatVersion);u16(p,kHeaderBytes);u16(p,kRecordBytes);u32(p,kI2cHz);u8(p,kSda);u8(p,kScl);u64(p,esp_timer_get_time());snprintf((char*)p,96,"INA226_BIN_V1 %s %s stage=%u",kFirmwareName,kFirmwareVersion,kActiveStage);p=b+kHeaderBytes-4;u32(p,crc(b,kHeaderBytes-4));file_.write(b,sizeof(b));}
bool Logger::openRun(){Preferences n;n.begin("inalog",false);uint32_t r=n.getUInt("next",1);for(uint16_t i=0;i<100;i++,r++){snprintf(stats_.runName,sizeof(stats_.runName),"RUN%04lu",(unsigned long)r);char p[32];snprintf(p,sizeof(p),"%s/%s.BIN",kLogDirectory,stats_.runName);if(!SD.exists(p)){file_=SD.open(p,FILE_WRITE);if(!file_){n.end();setFault("BIN create failed");return false;}n.putUInt("next",r+1);n.end();header();return true;}}n.end();setFault("RUN number exhausted");return false;}
void Logger::record(uint8_t*out,const Event&e,uint32_t s){memset(out,0,kRecordBytes);uint8_t*p=out;u32(p,RM);u16(p,kLogFormatVersion);u8(p,(uint8_t)e.type);u8(p,e.flags);u16(p,kRecordBytes);u32(p,s);u64(p,e.rxUs);u64(p,e.requestUs);u32(p,e.roundTripUs);u32(p,e.packetSequence);memcpy(p,e.payload,kPayloadBytes);p=out+kRecordBytes-4;u32(p,crc(out,kRecordBytes-4));}
void Logger::requestStart(){if(state_==State::Ready)start_=true;}void Logger::requestStop(){if(state_==State::Logging){Event e{};e.type=Type::LogEnd;e.rxUs=esp_timer_get_time();enqueue(e);stop_=true;}}void Logger::task(void*x){static_cast<Logger*>(x)->writer();}void Logger::writer(){for(;;){if(state_==State::Logging||state_==State::Stopping){busy_=true;uint8_t b[kSdWriteBlockBytes];size_t used=0;Event e;while(used+kRecordBytes<=sizeof(b)&&pop(e)){record(b+used,e,++seq_);used+=kRecordBytes;}if(used){if(file_.write(b,used)!=used){stats_.writeErrors++;state_=State::Error;setFault("SD block write failed");}else stats_.saved+=used/kRecordBytes;}if(millis()-lastFlushMs_>=kSdFlushIntervalMs){file_.flush();lastFlushMs_=millis();}busy_=false;}vTaskDelay(1);}}
void Logger::service(){if(start_){start_=false;if(openRun()){head_=tail_=count_=0;seq_=0;stats_.saved=stats_.dropped=stats_.writeErrors=stats_.queueHighWater=0;lastFlushMs_=millis();state_=State::Logging;}else state_=State::Error;}if(stop_){stop_=false;state_=State::Stopping;}if(state_==State::Stopping&&count_==0&&!busy_)closeRun();}void Logger::closeRun(){file_.flush();file_.close();state_=State::Ready;}bool Logger::writeSummary(const char*t){if(!stats_.mounted||!stats_.runName[0])return false;char p[32];snprintf(p,sizeof(p),"%s/%s.TXT",kLogDirectory,stats_.runName);SD.remove(p);File f=SD.open(p,FILE_WRITE);if(!f)return false;size_t n=strlen(t),w=f.write((const uint8_t*)t,n);f.flush();f.close();return w==n;}
}