#include <Arduino.h>
#include <Wire.h>
#include <WiFi.h>
#include <WebServer.h>
#include <esp_timer.h>
#include <cstring>
#include "app_config.h"
#include "pca9685.h"
#include "sd_logger.h"
using namespace cfg;
namespace {
WebServer web(80); Pca9685 pca; vlog::Logger logger;
enum class ControlState:uint8_t { Boot,Initializing,Disarmed,Armed,Moving,Estop,Fault };
ControlState state=ControlState::Boot;
uint16_t targetUs=kCenterUs,outputUs=kCenterUs; PcaChannel outputCounts{};
uint64_t lastControlUs=0,lastStatusUs=0,lastCommandUs=0; uint32_t lastHeartbeatMs=0;
uint32_t commandSequence=0,commands=0,accepted=0,rejected=0,outputs=0,armCount=0,disarmCount=0,estopCount=0,watchdogCount=0,faultCount=0,maxI2cUs=0,maxControlUs=0,minHeap=UINT32_MAX;
bool configLogged=false,summaryPending=false,estopLatched=false,endpointSweepActive=false,endpointSweepHigh=false; uint32_t endpointSweepStartMs=0,endpointSweepNextMs=0;
const char* stateName(ControlState s){switch(s){case ControlState::Boot:return "BOOT";case ControlState::Initializing:return "INITIALIZING";case ControlState::Disarmed:return "DISARMED";case ControlState::Armed:return "ARMED";case ControlState::Moving:return "MOVING";case ControlState::Estop:return "ESTOP";default:return "FAULT";}}
void u8(uint8_t*&p,uint8_t v){*p++=v;} void u16(uint8_t*&p,uint16_t v){u8(p,v>>8);u8(p,v);} void u32(uint8_t*&p,uint32_t v){for(int i=3;i>=0;--i)u8(p,v>>(8*i));} void u64(uint8_t*&p,uint64_t v){for(int i=7;i>=0;--i)u8(p,v>>(8*i));}
void oe(bool enabled){digitalWrite(kOe,enabled?LOW:HIGH);} // OE is active-low
void logState(ControlState before,ControlState after,uint8_t reason){if(!logger.isLogging())return;vlog::Event e{};e.type=vlog::Type::StateChange;e.rxUs=esp_timer_get_time();uint8_t*p=e.payload;u8(p,(uint8_t)before);u8(p,(uint8_t)after);u8(p,reason);u16(p,targetUs);u16(p,outputUs);logger.enqueue(e);}
void changeState(ControlState next,uint8_t reason){if(next==state)return;ControlState old=state;state=next;logState(old,next,reason);}
void safeDisable(){oe(false);if(pca.detected)pca.allOff();}
void commandLog(uint8_t source,uint16_t requested,bool ok,uint8_t reason){++commands;if(ok)++accepted;else ++rejected;vlog::Event e{};e.type=vlog::Type::ServoCommand;e.flags=ok?1:0;e.rxUs=esp_timer_get_time();e.packetSequence=++commandSequence;uint8_t*p=e.payload;u8(p,source);u8(p,kServoChannel);u16(p,requested);u16(p,targetUs);u8(p,(uint8_t)state);u8(p,reason);logger.enqueue(e);}
void outputLog(bool slew,bool writeOk,uint32_t i2cUs){if(!logger.isLogging())return;vlog::Event e{};e.type=vlog::Type::ServoOutput;e.flags=(slew?1:0)|(writeOk?2:0)|(outputCounts.fullOff?4:0);e.rxUs=esp_timer_get_time();uint8_t*p=e.payload;u8(p,kServoChannel);u8(p,(uint8_t)state);u16(p,targetUs);u16(p,outputUs);u16(p,outputCounts.on);u16(p,outputCounts.off);u8(p,digitalRead(kOe)==LOW?1:0);u32(p,i2cUs);logger.enqueue(e);}
void eventLog(vlog::Type t,uint8_t reason){if(!logger.isLogging())return;vlog::Event e{};e.type=t;e.rxUs=esp_timer_get_time();uint8_t*p=e.payload;u8(p,reason);u8(p,(uint8_t)state);u16(p,targetUs);u16(p,outputUs);logger.enqueue(e);}
void disarm(uint8_t reason){endpointSweepActive=false;safeDisable();targetUs=outputUs=kCenterUs;++disarmCount;changeState(ControlState::Disarmed,reason);}
void estop(uint8_t reason){endpointSweepActive=false;estopLatched=true;safeDisable();++estopCount;changeState(ControlState::Estop,reason);eventLog(vlog::Type::EstopEvent,reason);}
void fault(uint8_t reason){endpointSweepActive=false;safeDisable();++faultCount;changeState(ControlState::Fault,reason);eventLog(vlog::Type::PcaStatus,reason);}
bool arm(){if(state!=ControlState::Disarmed||estopLatched||!pca.detected){commandLog(1,kCenterUs,false,1);return false;}targetUs=outputUs=kCenterUs;uint64_t t=esp_timer_get_time();bool ok=pca.setPulse(kServoChannel,outputUs,&outputCounts);uint32_t dt=(uint32_t)(esp_timer_get_time()-t);if(dt>maxI2cUs)maxI2cUs=dt;if(!ok){fault(2);commandLog(1,kCenterUs,false,2);return false;}oe(true);lastHeartbeatMs=millis();lastCommandUs=esp_timer_get_time();++armCount;changeState(ControlState::Armed,2);commandLog(1,kCenterUs,true,0);outputLog(false,true,dt);return true;}
bool setTarget(uint16_t us,uint8_t source){if(state!=ControlState::Armed&&state!=ControlState::Moving){commandLog(source,us,false,3);return false;}if(us<kHardMinUs||us>kHardMaxUs){commandLog(source,us,false,4);return false;}if(source!=2)endpointSweepActive=false;targetUs=us;lastCommandUs=esp_timer_get_time();commandLog(source,us,true,0);return true;}
bool startEndpointSweep(){if(endpointSweepActive||(state!=ControlState::Armed&&state!=ControlState::Moving))return false;uint32_t now=millis();endpointSweepHigh=false;if(!setTarget(kTestMinUs,2))return false;endpointSweepStartMs=now;endpointSweepNextMs=now+kEndpointSweepHalfPeriodMs;endpointSweepActive=true;lastHeartbeatMs=now;return true;}
void endpointSweepService(){if(!endpointSweepActive)return;uint32_t now=millis();lastHeartbeatMs=now;if((uint32_t)(now-endpointSweepStartMs)>=kEndpointSweepDurationMs){disarm(12);return;}if((int32_t)(now-endpointSweepNextMs)>=0){endpointSweepHigh=!endpointSweepHigh;setTarget(endpointSweepHigh?kTestMaxUs:kTestMinUs,2);endpointSweepNextMs+=kEndpointSweepHalfPeriodMs;if((int32_t)(now-endpointSweepNextMs)>=0)endpointSweepNextMs=now+kEndpointSweepHalfPeriodMs;}}
void control(){uint64_t now=esp_timer_get_time();if(now-lastControlUs<kControlUs)return;uint32_t interval=lastControlUs?(uint32_t)(now-lastControlUs):0;lastControlUs=now;if(interval>maxControlUs)maxControlUs=interval;if(state!=ControlState::Armed&&state!=ControlState::Moving)return;if((uint32_t)(millis()-lastHeartbeatMs)>kHeartbeatTimeoutMs){safeDisable();++watchdogCount;changeState(ControlState::Disarmed,5);eventLog(vlog::Type::WatchdogEvent,5);return;}int d=(int)targetUs-(int)outputUs;int step=(int)((kSlewUsPerSecond+kControlHz-1)/kControlHz);if(d>step)d=step;if(d<-step)d=-step;bool slew=d!=0;outputUs=(uint16_t)((int)outputUs+d);uint64_t t=esp_timer_get_time();bool ok=pca.setPulse(kServoChannel,outputUs,&outputCounts);uint32_t dt=(uint32_t)(esp_timer_get_time()-t);if(dt>maxI2cUs)maxI2cUs=dt;if(!ok){fault(6);return;}++outputs;outputLog(slew,true,dt);changeState(outputUs==targetUs?ControlState::Armed:ControlState::Moving,6);}
void logConfig(){if(!logger.isLogging()||configLogged)return;vlog::Event e{};e.type=vlog::Type::PcaConfig;e.flags=pca.detected?1:0;e.rxUs=esp_timer_get_time();uint8_t*p=e.payload;u32(p,kPcaAddress);u32(p,kI2cHz);u32(p,kOscillatorHz);u32(p,(uint32_t)(pca.actualHz*1000));u8(p,pca.mode1);u8(p,pca.mode2);u8(p,pca.prescale);u8(p,kServoChannel);u16(p,kHardMinUs);u16(p,kTestMinUs);u16(p,kCenterUs);u16(p,kTestMaxUs);u16(p,kHardMaxUs);logger.enqueue(e);configLogged=true;}
void statusLog(){uint64_t now=esp_timer_get_time();if(!logger.isLogging()||now-lastStatusUs<1000000ULL)return;lastStatusUs=now;vlog::Event e{};e.type=vlog::Type::PcaStatus;e.flags=pca.detected?1:0;e.rxUs=now;uint8_t*p=e.payload;u8(p,(uint8_t)state);u8(p,digitalRead(kOe)==LOW?1:0);u8(p,pca.mode1);u8(p,pca.mode2);u8(p,pca.prescale);u16(p,targetUs);u16(p,outputUs);u32(p,pca.errors);u32(p,pca.readbackErrors);u32(p,estopCount);u32(p,watchdogCount);u32(p,(uint32_t)(millis()-lastHeartbeatMs));u32(p,maxI2cUs);logger.enqueue(e);}
void writeSummary(){if(!summaryPending||logger.isLogging()||logger.state()!=vlog::State::Ready)return;char b[900];snprintf(b,sizeof(b),"firmware=%s\nversion=%s\naddress=0x%02X\nsda=%d\nscl=%d\ni2c_hz=%lu\noe_pin=%d\npwm_hz=%.4f\nmode1=0x%02X\nmode2=0x%02X\nprescale=%u\nchannel=%u\nhard_min_us=%u\ntest_min_us=%u\ncenter_us=%u\ntest_max_us=%u\nhard_max_us=%u\nslew_us_per_s=%u\ncommands=%lu\naccepted=%lu\nrejected=%lu\noutputs=%lu\narms=%lu\ndisarms=%lu\nestops=%lu\nwatchdogs=%lu\nfaults=%lu\ni2c_errors=%lu\nreadback_errors=%lu\nmax_i2c_us=%lu\nmax_control_us=%lu\nqueue_highwater=%lu\nqueue_drop=%lu\nsd_write_errors=%lu\nmin_free_heap=%lu\nnormal_stop=1\n",kFirmwareName,kFirmwareVersion,kPcaAddress,kSda,kScl,(unsigned long)kI2cHz,kOe,pca.actualHz,pca.mode1,pca.mode2,pca.prescale,kServoChannel,kHardMinUs,kTestMinUs,kCenterUs,kTestMaxUs,kHardMaxUs,kSlewUsPerSecond,(unsigned long)commands,(unsigned long)accepted,(unsigned long)rejected,(unsigned long)outputs,(unsigned long)armCount,(unsigned long)disarmCount,(unsigned long)estopCount,(unsigned long)watchdogCount,(unsigned long)faultCount,(unsigned long)pca.errors,(unsigned long)pca.readbackErrors,(unsigned long)maxI2cUs,(unsigned long)maxControlUs,(unsigned long)logger.stats().queueHighWater,(unsigned long)logger.stats().dropped,(unsigned long)logger.stats().writeErrors,(unsigned long)minHeap);if(logger.writeSummary(b))summaryPending=false;}
void apiStatus(){uint32_t age=(state==ControlState::Armed||state==ControlState::Moving)?(uint32_t)(millis()-lastHeartbeatMs):0;uint32_t rem=0;if(endpointSweepActive){uint32_t elapsed=(uint32_t)(millis()-endpointSweepStartMs);rem=elapsed>=kEndpointSweepDurationMs?0:kEndpointSweepDurationMs-elapsed;}char b[1100];snprintf(b,sizeof(b),"{\"detected\":%s,\"address\":\"0x%02X\",\"state\":\"%s\",\"oe_enabled\":%s,\"pwm_hz\":%.4f,\"mode1\":\"0x%02X\",\"mode2\":\"0x%02X\",\"prescale\":%u,\"target_us\":%u,\"output_us\":%u,\"count\":%u,\"endpoint_sweep_active\":%s,\"endpoint_sweep_remaining_ms\":%lu,\"heartbeat_age_ms\":%lu,\"i2c_errors\":%lu,\"readback_errors\":%lu,\"estops\":%lu,\"watchdogs\":%lu,\"sd_state\":\"%s\",\"run\":\"%s\",\"queue\":%lu,\"drops\":%lu,\"sd_errors\":%lu,\"free_heap\":%lu}",pca.detected?"true":"false",kPcaAddress,stateName(state),digitalRead(kOe)==LOW?"true":"false",pca.actualHz,pca.mode1,pca.mode2,pca.prescale,targetUs,outputUs,outputCounts.off,endpointSweepActive?"true":"false",(unsigned long)rem,(unsigned long)age,(unsigned long)pca.errors,(unsigned long)pca.readbackErrors,(unsigned long)estopCount,(unsigned long)watchdogCount,logger.stateName(),logger.stats().runName,(unsigned long)logger.stats().queueUsed,(unsigned long)logger.stats().dropped,(unsigned long)logger.stats().writeErrors,(unsigned long)ESP.getFreeHeap());web.send(200,"application/json",b);}
void startLog(){configLogged=false;summaryPending=false;logger.requestStart();web.send(202,"application/json","{\"accepted\":true}");}
void stopLog(){if(state==ControlState::Armed||state==ControlState::Moving)disarm(7);logger.requestStop();summaryPending=true;web.send(202,"application/json","{\"accepted\":true}");}
void pulseApi(){long x=web.arg("us").toInt();bool ok=setTarget((uint16_t)x,1);web.send(ok?200:409,"application/json",ok?"{\"accepted\":true}":"{\"accepted\":false}");}
void endpointSweepApi(){bool ok=startEndpointSweep();web.send(ok?202:409,"application/json",ok?"{\"accepted\":true}":"{\"accepted\":false}");}
void heartbeat(){if(state==ControlState::Armed||state==ControlState::Moving){lastHeartbeatMs=millis();web.send(200,"application/json","{\"accepted\":true}");}else web.send(409,"application/json","{\"accepted\":false}");}
const char page[]=R"HTML(<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><style>body{font:15px system-ui;background:#101820;color:#e8eef5}.c{margin:8px;padding:10px;background:#1d2935;border-radius:8px;white-space:pre-wrap}button{padding:9px;margin:3px}canvas{width:100%;height:150px;background:#0b1118}</style><h2 class=c>PCA9685 Servo safety test</h2><div class=c id=s>loading</div><div class=c><button onclick="post('/api/log/start')">Start log</button><button onclick="post('/api/log/stop')">Stop log</button><button onclick="post('/api/arm')">Arm</button><button onclick="post('/api/disarm')">Disarm</button><button onclick="post('/api/estop')">E-STOP</button><br><button onclick="pulse(1500)">Center</button><button onclick="pulse(1490)">-10 us</button><button onclick="pulse(1510)">+10 us</button><button onclick="pulse(500)">500 lower</button><button onclick="pulse(1400)">1400</button><button onclick="pulse(1600)">1600</button><button onclick="pulse(2500)">2500 upper</button><br><button onclick="post('/api/sweep/start')">10 s endpoint sweep</button></div><canvas id=g width=800 height=150></canvas><div class=c id=d></div><script>const history=[];function draw(){let c=g.getContext("2d"),w=g.width,h=g.height;c.clearRect(0,0,w,h);if(history.length<2)return;let mn=Math.min(...history),mx=Math.max(...history);if(mx-mn<2){mn-=2;mx+=2}c.strokeStyle="#55d890";c.beginPath();history.forEach((v,i)=>{let x=i*w/(history.length-1),y=h-(v-mn)/(mx-mn)*h;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();c.fillStyle="#e8eef5";c.fillText("output pulse "+mn.toFixed(0)+" - "+mx.toFixed(0)+" us",8,16)}async function post(u){try{await fetch(u,{method:'POST'});setTimeout(load,100)}catch(e){s.textContent='request failed'}}function pulse(x){post('/api/pulse?us='+x)}async function load(){try{let j=await(await fetch('/api/status',{cache:'no-store'})).json();s.textContent='PCA '+(j.detected?'DETECTED':'NOT DETECTED')+' '+j.address+' '+j.state+' OE='+j.oe_enabled+' PWM='+j.pwm_hz+'Hz | '+j.sd_state+' '+j.run+' q='+j.queue+' drop='+j.drops+' SDerr='+j.sd_errors;d.textContent='target '+j.target_us+' us, output '+j.output_us+' us, count '+j.count+' | sweep '+(j.endpoint_sweep_active?j.endpoint_sweep_remaining_ms+' ms':'off')+'\nheartbeat '+j.heartbeat_age_ms+' ms | I2C '+j.i2c_errors+' readback '+j.readback_errors+' | ESTOP '+j.estops+' watchdog '+j.watchdogs+' | heap '+j.free_heap;history.push(j.output_us);if(history.length>120)history.shift();draw();if(j.state==='ARMED'||j.state==='MOVING')fetch('/api/heartbeat',{method:'POST'})}catch(e){s.textContent='Web update failed'}}setInterval(load,500);load()</script>)HTML";
void serialDiag(){static uint32_t last=0;if(millis()-last<1000)return;last=millis();uint32_t h=ESP.getFreeHeap();if(h<minHeap)minHeap=h;Serial.printf("PCA=%d state=%s OE=%d target=%u output=%u count=%u hb=%lums I2C=%lu rb=%lu SD=%s q=%lu drop=%lu\n",pca.detected,stateName(state),digitalRead(kOe)==LOW,targetUs,outputUs,outputCounts.off,(unsigned long)(millis()-lastHeartbeatMs),(unsigned long)pca.errors,(unsigned long)pca.readbackErrors,logger.stateName(),(unsigned long)logger.stats().queueUsed,(unsigned long)logger.stats().dropped);}
}
void setup(){Serial.begin(115200);pinMode(kOe,OUTPUT);oe(false);delay(100);changeState(ControlState::Initializing,0);Wire.begin(kSda,kScl,kI2cHz);Wire.setTimeOut(20);bool ok=pca.begin();safeDisable();if(ok)changeState(ControlState::Disarmed,1);else fault(1);logger.begin();WiFi.mode(WIFI_AP);WiFi.softAP(kApSsid,kApPass);web.on("/",HTTP_GET,[]{web.send(200,"text/html",page);});web.on("/api/status",HTTP_GET,apiStatus);web.on("/api/log/start",HTTP_POST,startLog);web.on("/api/log/stop",HTTP_POST,stopLog);web.on("/api/arm",HTTP_POST,[]{bool ok=arm();web.send(ok?200:409,"application/json",ok?"{\"accepted\":true}":"{\"accepted\":false}");});web.on("/api/disarm",HTTP_POST,[]{if(state==ControlState::Armed||state==ControlState::Moving)disarm(3);web.send(200,"application/json","{\"accepted\":true}");});web.on("/api/estop",HTTP_POST,[]{estop(4);web.send(200,"application/json","{\"accepted\":true}");});web.on("/api/pulse",HTTP_POST,pulseApi);web.on("/api/sweep/start",HTTP_POST,endpointSweepApi);web.on("/api/heartbeat",HTTP_POST,heartbeat);web.begin();lastControlUs=esp_timer_get_time();Serial.printf("%s %s AP=%s IP=%s\n",kFirmwareName,kFirmwareVersion,kApSsid,WiFi.softAPIP().toString().c_str());}
void loop(){logger.service();logConfig();endpointSweepService();control();statusLog();web.handleClient();writeSummary();serialDiag();delay(1);}