#include <Arduino.h>
#include <Wire.h>
#include <WiFi.h>
#include <WebServer.h>
#include <SparkFun_VL53L5CX_Library.h>
#include <esp_timer.h>
#include "app_config.h"
#include "safety_state.h"
#include "bno_reader.h"
#include "ina226_reader.h"
#include "pca9685.h"
#include "vesc_protocol.h"
#include <boat_protocol.h>
using namespace app_config;
WebServer web(kDebugHttpPort); HardwareSerial vescUart(1),linkUart(2); SparkFun_VL53L5CX tof; VL53L5CX_ResultsData tofData{}; bno::Reader imu; Ina226 ina; Pca9685 pca; vesc::Parser vescParser; vesc::Values vescValues{};
SafetyState safety=SafetyState::BOOT; TestProfile profile=TestProfile::None; bool tofReady=false,inaReady=false,pcaReady=false; uint32_t bootId=0,lastInaUs=0,lastTofUs=0,lastVescReqMs=0,lastDutyMs=0,testStartMs=0,lastDiagMs=0; uint16_t servoTarget=kServoCenterUs,servoOutput=kServoCenterUs; uint32_t tofFrames=0,vescReq=0,vescResp=0,vescErrors=0,linkSeq=0,linkDrops=0,linkQueueHighWater=0,linkRxFrames=0,linkStopCommands=0,linkEstopCommands=0; boat::Decoder linkDecoder; struct TxItem{uint16_t length=0,offset=0;uint8_t data[boat::kMaxEncoded]{};}; constexpr uint8_t kLinkQueueDepth=96; TxItem linkQueue[kLinkQueueDepth]{};uint8_t linkHead=0,linkTail=0,linkUsed=0;portMUX_TYPE linkMux=portMUX_INITIALIZER_UNLOCKED;
uint64_t nowUs(){return esp_timer_get_time();}
void linkSend(boat::Type type,const uint8_t*p,uint16_t n,uint16_t flags=0){uint8_t encoded[boat::kMaxEncoded];boat::Header h{boat::kVersion,(uint8_t)type,n,++linkSeq,bootId,nowUs(),flags};uint16_t length=(uint16_t)boat::encode(h,p,encoded,sizeof(encoded));if(!length){linkDrops++;return;}portENTER_CRITICAL(&linkMux);if(linkUsed>=kLinkQueueDepth){linkDrops++;portEXIT_CRITICAL(&linkMux);return;}TxItem&x=linkQueue[linkHead];x.offset=0;x.length=length;memcpy(x.data,encoded,length);linkHead=(linkHead+1)%kLinkQueueDepth;linkUsed++;if(linkUsed>linkQueueHighWater)linkQueueHighWater=linkUsed;portEXIT_CRITICAL(&linkMux);}
void linkService(){while(true){portENTER_CRITICAL(&linkMux);if(!linkUsed){portEXIT_CRITICAL(&linkMux);return;}TxItem*x=&linkQueue[linkTail];uint16_t offset=x->offset,length=x->length;portEXIT_CRITICAL(&linkMux);int room=linkUart.availableForWrite();if(room<=0)return;size_t remain=length-offset,want=remain<(size_t)room?remain:(size_t)room;size_t done=linkUart.write(x->data+offset,want);if(!done)return;portENTER_CRITICAL(&linkMux);x->offset+=done;if(x->offset>=x->length){linkTail=(linkTail+1)%kLinkQueueDepth;linkUsed--;}portEXIT_CRITICAL(&linkMux);}}
void linkTxTask(void*){for(;;){linkService();vTaskDelay(1);}}uint16_t crc16(const uint8_t*d,size_t n){return vesc::Parser::crc16(d,n);} void vescSend(const uint8_t*p,uint8_t n){uint16_t c=crc16(p,n);vescUart.write(2);vescUart.write(n);vescUart.write(p,n);vescUart.write(c>>8);vescUart.write(c);vescUart.write(3);} void vescDuty(float duty){int32_t x=(int32_t)(constrain(duty,-kVescMaxDuty,kVescMaxDuty)*100000.0f);uint8_t p[5]={5,(uint8_t)(x>>24),(uint8_t)(x>>16),(uint8_t)(x>>8),(uint8_t)x};vescSend(p,5);} void safeOutputs(){vescDuty(0);if(pcaReady)pca.allOff();servoOutput=kServoCenterUs;}
void setState(SafetyState n){if(n==safety)return;safety=n;Serial.printf("STATE %s\n",stateName(safety));}
void bnoEvent(const bno::Sample&s){struct __attribute__((packed)){uint8_t kind,accuracy,sequence;uint8_t reserved;uint64_t sensorUs;float v[7];} p{};p.kind=(uint8_t)s.type;p.accuracy=s.accuracy;p.sequence=s.sequence;p.sensorUs=s.sensorUs;memcpy(p.v,s.v,sizeof(p.v));linkSend(s.type==bno::EventType::Accel?boat::Type::BnoAccel:s.type==bno::EventType::Gyro?boat::Type::BnoGyro:boat::Type::BnoQuaternion,(uint8_t*)&p,sizeof(p));}
void scan(){char a[96]="";size_t used=0;for(uint8_t x=8;x<120;x++){Wire.beginTransmission(x);if(!Wire.endTransmission())used+=snprintf(a+used,sizeof(a)-used,"%s0x%02X",used?",":"",x);}Serial.printf("PERIPH_SCAN %s\n",used?a:"none");}
void pollTof(){if(!tofReady||!tof.isDataReady())return;uint64_t t=nowUs();if(!tof.getRangingData(&tofData))return;tofFrames++;lastTofUs=t;uint8_t p[196];memcpy(p,&tofFrames,4);memcpy(p+4,tofData.distance_mm,128);memcpy(p+132,tofData.target_status,64);linkSend(boat::Type::TofFrame,p,sizeof(p));}
void pollIna(){if((uint32_t)(nowUs()-lastInaUs)<kInaSampleUs)return;lastInaUs=nowUs();InaSample s{};if(inaReady)ina.read(s);if(s.valid){struct __attribute__((packed)){int16_t shunt,current;uint16_t bus,power,mask;uint32_t i2cUs;} p{s.rawShunt,s.rawCurrent,s.rawBus,s.rawPower,s.mask,s.i2cUs};linkSend(boat::Type::InaSample,(uint8_t*)&p,sizeof(p));}if(s.valid&&kEnableOverCurrentTrip&&fabsf(s.currentRegA)>kOverCurrentTripA){safeOutputs();setState(SafetyState::FAULT);}}
void pollVesc(){while(vescUart.available()){vesc::Frame f{};vesc::ParseError e; if(vescParser.feed((uint8_t)vescUart.read(),nowUs(),f,e)){if(f.crcOk&&f.endOk&&vesc::Parser::parseCurrentValues(f,vescValues)){vescResp++;linkSend(boat::Type::VescStatus,(uint8_t*)&vescValues,sizeof(vescValues));}else vescErrors++;}}if(millis()-lastVescReqMs>=kVescRequestIntervalMs){lastVescReqMs=millis();uint8_t p=4;vescSend(&p,1);vescReq++;}}
void stop(); void linkRxService(){while(linkUart.available()){boat::Frame f{};if(!linkDecoder.feed((uint8_t)linkUart.read(),f))continue;++linkRxFrames;boat::Type type=(boat::Type)f.header.type;if(type==boat::Type::Stop){++linkStopCommands;stop();}else if(type==boat::Type::Estop){++linkEstopCommands;safeOutputs();profile=TestProfile::None;setState(SafetyState::E_STOP);}}}
void control(){if(safety!=SafetyState::RUNNING)return;if(millis()-testStartMs>=kMaxTestMs){safeOutputs();setState(SafetyState::DISARMED);return;}if(profile==TestProfile::ServoCenter)servoTarget=kServoCenterUs;else if(profile==TestProfile::ServoSlow){uint32_t phase=(millis()-testStartMs)/1000;servoTarget=(phase&1)?kServoIntegrationMaxUs:kServoIntegrationMinUs;}else if(profile==TestProfile::ServoVesc){uint32_t phase=(millis()-testStartMs)/1000;servoTarget=(phase&1)?kServoIntegrationMaxUs:kServoIntegrationMinUs;}if(profile==TestProfile::ServoCenter||profile==TestProfile::ServoSlow||profile==TestProfile::ServoVesc){int d=(int)servoTarget-(int)servoOutput;d=constrain(d,-(int)kServoSlewUsPerUpdate,(int)kServoSlewUsPerUpdate);servoOutput+=d;pca.setPulse(kServoChannel,servoOutput);}if(profile==TestProfile::VescDuty||profile==TestProfile::ServoVesc){if(millis()-lastDutyMs>=kVescKeepaliveMs){lastDutyMs=millis();vescDuty(kVescTestDuty);}}}
void start(TestProfile p){if(safety!=SafetyState::ARMED_IDLE)return;profile=p;testStartMs=millis();setState(SafetyState::RUNNING);} void stop(){safeOutputs();profile=TestProfile::None;if(safety!=SafetyState::E_STOP)setState(SafetyState::DISARMED);} void command(const char*c){if(!strcmp(c,"help"))Serial.println("help status scan arm disarm stop estop clear_estop sensors_start sensors_stop servo_center servo_slow_test vesc_status_test vesc_3percent_test diag_on diag_off");else if(!strcmp(c,"status"))Serial.printf("%s BNO=%d TOF=%d INA=%d PCA=%d VESC=%lu/%lu\n",stateName(safety),imu.ready(),tofReady,inaReady,pcaReady,vescResp,vescReq);else if(!strcmp(c,"scan"))scan();else if(!strcmp(c,"arm")&&safety==SafetyState::DISARMED)setState(SafetyState::ARMED_IDLE);else if(!strcmp(c,"disarm")||!strcmp(c,"stop"))stop();else if(!strcmp(c,"estop")){safeOutputs();setState(SafetyState::E_STOP);}else if(!strcmp(c,"clear_estop")&&safety==SafetyState::E_STOP)setState(SafetyState::DISARMED);else if(!strcmp(c,"sensors_start"))start(TestProfile::SensorOnly);else if(!strcmp(c,"servo_center"))start(TestProfile::ServoCenter);else if(!strcmp(c,"servo_slow_test"))start(TestProfile::ServoSlow);else if(!strcmp(c,"vesc_status_test"))start(TestProfile::VescStatus);else if(!strcmp(c,"vesc_3percent_test"))start(TestProfile::VescDuty);}
void serialConsole(){static char b[64];static uint8_t n=0;while(Serial.available()){char c=Serial.read();if(c=='\n'||c=='\r'){if(n){b[n]=0;command(b);n=0;}}else if(n<sizeof(b)-1)b[n++]=c;}}
void webStatus(){char b[700];snprintf(b,sizeof(b),"{\"firmware\":\"%s\",\"state\":\"%s\",\"bno_ready\":%s,\"bno_addr\":\"0x%02X\",\"tof_ready\":%s,\"tof_frames\":%lu,\"ina_ready\":%s,\"ina_errors\":%lu,\"pca_ready\":%s,\"vesc_erpm\":%.1f,\"vesc_duty\":%.4f,\"vesc_requests\":%lu,\"vesc_responses\":%lu,\"vesc_errors\":%lu,\"link_queue\":%u,\"link_drops\":%lu,\"link_highwater\":%lu}",kFirmwareVersion,stateName(safety),imu.ready()?"true":"false",imu.address(),tofReady?"true":"false",tofFrames,inaReady?"true":"false",(unsigned long)ina.errors,pcaReady?"true":"false",vescValues.erpm,vescValues.duty,vescReq,vescResp,vescErrors,linkUsed,(unsigned long)linkDrops,(unsigned long)linkQueueHighWater);web.send(200,"application/json",b);} const char webPage[]=R"HTML(<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><style>body{font:16px system-ui;background:#101820;color:#e8eef5}.c{margin:10px;padding:12px;background:#1d2935;border-radius:8px;white-space:pre-wrap}</style><h2 class=c>XIAO boat integration: bench status</h2><div class=c id="s">loading</div><div class=c>Temporary read-only Wi-Fi diagnostic. No actuator controls are available here.</div><script>async function u(){try{let j=await(await fetch("/api/status",{cache:"no-store"})).json();s.textContent=`State: ${j.state}\nBNO: ${j.bno_ready} ${j.bno_addr}\nToF: ${j.tof_ready}, frames ${j.tof_frames}\nINA: ${j.ina_ready}, errors ${j.ina_errors}\nPCA: ${j.pca_ready}\nVESC: ${j.vesc_erpm.toFixed(1)} ERPM, duty ${j.vesc_duty.toFixed(4)}\nVESC request/response/error: ${j.vesc_requests}/${j.vesc_responses}/${j.vesc_errors}\nLink queue/drop/high-water: ${j.link_queue}/${j.link_drops}/${j.link_highwater}`}catch(e){s.textContent="update failed"}}setInterval(u,1000);u()</script>)HTML"; void startDebugWifi(){if(!kEnableTemporaryDebugWifi)return;WiFi.mode(WIFI_AP);WiFi.softAP(kDebugApSsid,kDebugApPass);web.on("/",HTTP_GET,[]{web.send(200,"text/html",webPage);});web.on("/api/status",HTTP_GET,webStatus);web.begin();Serial.printf("DEBUG_WIFI SSID=%s IP=%s\n",kDebugApSsid,WiFi.softAPIP().toString().c_str());} void setup(){Serial.begin(115200);delay(100);bootId=esp_random();Wire.begin(kPeripheralSdaPin,kPeripheralSclPin,kPeripheralI2cHz);Wire.setTimeOut(20);scan();pcaReady=pca.begin();safeOutputs();inaReady=ina.begin();tofReady=tof.begin(kTofAddress,Wire)&&tof.setResolution(64)&&tof.setRangingFrequency(kTofFrequencyHz)&&tof.setRangingMode(SF_VL53L5CX_RANGING_MODE::CONTINUOUS)&&tof.startRanging();imu.begin();vescUart.begin(kVescUartBaud,SERIAL_8N1,kVescRxPin,kVescTxPin);linkUart.begin(kLinkBaud,SERIAL_8N1,kLinkRxPin,kLinkTxPin);xTaskCreatePinnedToCore(linkTxTask,"LinkTx",4096,nullptr,2,nullptr,0);startDebugWifi();setState(SafetyState::DISARMED);Serial.printf("%s %s boot=%lu\n",kFirmwareName,kFirmwareVersion,bootId);}
void loop(){if(kEnableTemporaryDebugWifi)web.handleClient();serialConsole();linkRxService();imu.poll(bnoEvent);imu.recover();pollTof();pollIna();pollVesc();control();if(millis()-lastDiagMs>=kDiagnosticIntervalMs){lastDiagMs=millis();Serial.printf("DIAG state=%s bno=%d tof=%lu ina_err=%lu pca=%d vesc=%.0f erpm %.2f duty req/rsp=%lu/%lu link_rx=%lu stop/estop=%lu/%lu\n",stateName(safety),imu.ready(),tofFrames,(unsigned long)ina.errors,pcaReady,vescValues.erpm,vescValues.duty,vescReq,vescResp,(unsigned long)linkRxFrames,(unsigned long)linkStopCommands,(unsigned long)linkEstopCommands);}delay(1);}
