#include "competition_shadow.h"
#include <cmath>

namespace competition_shadow {
namespace { constexpr float kPi = 3.14159265358979323846f; float wrap(float x) { while (x > kPi) x -= 2 * kPi; while (x < -kPi) x += 2 * kPi; return x; } }
Controller::Controller(const Config& config) : config_(config) { reset(); }
void Controller::reset() { safety_=SafetyState::Disarmed; mode_=ControlMode::Manual; manual_={}; manualReceivedUs_=0; lastModeRequest_=lastManualRequest_=lastHeadingRequest_=lastWaypointRequest_=0; targetYaw_=0; headingSet_=false; waypointCount_=activeWaypoint_=0; previous_[0]=previous_[1]=previous_[2]=previous_[3]=0; physicalWriteCount_=0; }
bool Controller::finite(float x) const { return std::isfinite(x); }
bool Controller::fresh(bool valid,uint64_t t,uint64_t now,uint32_t max) const { return valid && t && now>=t && now-t<=max; }
CommandResult Controller::setMode(ControlMode mode,uint32_t id) { if (id && id==lastModeRequest_) return {Ack::Duplicate,0}; if(safety_!=SafetyState::Disarmed) return {Ack::Rejected,1}; if((uint8_t)mode>3) return {Ack::Rejected,2}; lastModeRequest_=id; mode_=mode; return {Ack::Accepted,0}; }
CommandResult Controller::setManual(const ManualCommand& c,uint64_t received) { if(c.requestId && c.requestId==lastManualRequest_) return {Ack::Duplicate,0}; if(!finite(c.leftFront)||!finite(c.rightFront)||!finite(c.rearYaw)||!finite(c.propulsion)) return {Ack::Rejected,3}; if(c.leftFront < -1||c.leftFront>1||c.rightFront < -1||c.rightFront>1||c.rearYaw < -1||c.rearYaw>1||c.propulsion < 0||c.propulsion>1) return {Ack::Rejected,4}; lastManualRequest_=c.requestId; manual_=c; manualReceivedUs_=received; return {Ack::Accepted,0}; }
CommandResult Controller::setHeading(float yaw,uint32_t id) { if(id && id==lastHeadingRequest_) return {Ack::Duplicate,0}; if(!finite(yaw)) return {Ack::Rejected,3}; lastHeadingRequest_=id; targetYaw_=wrap(yaw); headingSet_=true; return {Ack::Accepted,0}; }
CommandResult Controller::setWaypoints(const Waypoint* p,uint8_t count,uint32_t id) { if(id && id==lastWaypointRequest_) return {Ack::Duplicate,0}; if(safety_!=SafetyState::Disarmed||!p||!count||count>16) return {Ack::Rejected,5}; for(uint8_t i=0;i<count;++i) if(!finite(p[i].northM)||!finite(p[i].eastM)) return {Ack::Rejected,3}; lastWaypointRequest_=id; for(uint8_t i=0;i<count;++i)waypoints_[i]=p[i]; waypointCount_=count; activeWaypoint_=0; return {Ack::Accepted,0}; }
bool Controller::physicalConfigurationValid(const PhysicalConfig& c) { const uint8_t a[]={c.leftChannel,c.rightChannel,c.rearChannel,c.propulsionChannel}; for(uint8_t i=0;i<4;++i){if(a[i]>15)return false;for(uint8_t j=i+1;j<4;++j)if(a[i]==a[j])return false;} return c.leftMinUs<c.leftCenterUs&&c.leftCenterUs<c.leftMaxUs&&c.rightMinUs<c.rightCenterUs&&c.rightCenterUs<c.rightMaxUs&&c.rearMinUs<c.rearCenterUs&&c.rearCenterUs<c.rearMaxUs&&c.propMinUs<c.propStopUs&&c.propStopUs<c.propMaxUs&&c.calibrationComplete; }
float Controller::limit(float value,float previous,bool& saturated) const { if(value>1){value=1;saturated=true;} if(value<-1){value=-1;saturated=true;} const float d=value-previous; if(d>config_.slewPerStep){value=previous+config_.slewPerStep;saturated=true;} if(d<-config_.slewPerStep){value=previous-config_.slewPerStep;saturated=true;} return value; }
void Controller::safe(Output&o,StopReason r){o.leftFront=o.rightFront=o.rearYaw=o.propulsion=0;o.reason=r;o.safety=safety_;o.physicalGate=false;previous_[0]=previous_[1]=previous_[2]=previous_[3]=0;}
Output Controller::step(const SensorInput& in,bool start,bool stop,bool estop,bool clear){ Output o{}; if(estop){safety_=SafetyState::EStop;} else if(clear&&safety_==SafetyState::EStop){safety_=SafetyState::Disarmed;} else if(stop){safety_=SafetyState::Disarmed;} else if(start&&safety_==SafetyState::ArmedIdle){safety_=SafetyState::Running;if(mode_==ControlMode::HeadingHold&&!headingSet_){targetYaw_=wrap(in.yawRad);headingSet_=true;}} else if(start&&safety_==SafetyState::Disarmed){safety_=SafetyState::ArmedIdle;}
  o.safety=safety_;o.mode=mode_;o.activeWaypoint=activeWaypoint_;
  if(safety_!=SafetyState::Running){safe(o,safety_==SafetyState::EStop?StopReason::EStop:(stop?StopReason::Stop:StopReason::None));return o;}
  if(!fresh(in.heartbeat,in.heartbeatUs,in.nowUs,config_.heartbeatStaleUs)){safety_=SafetyState::Fault;safe(o,StopReason::Heartbeat);return o;} if(in.vescFault){safety_=SafetyState::Fault;safe(o,StopReason::VescFault);return o;}
  const bool manualMode=mode_==ControlMode::Manual; const bool needsImu=!manualMode; const bool needsTof=!manualMode; const bool needsGnss=mode_==ControlMode::AutoWaypoint;
  if(manualMode&&!fresh(true,manualReceivedUs_,in.nowUs,config_.manualStaleUs)){safety_=SafetyState::Disarmed;safe(o,StopReason::ManualTimeout);return o;}
  if(needsImu&&(!in.imuValid||!fresh(in.imuValid,in.imuUs,in.nowUs,config_.imuStaleUs))){safety_=SafetyState::Fault;safe(o,in.imuValid?StopReason::ImuStale:StopReason::ImuInvalid);return o;}
  if(needsTof&&(!in.tofValid||!fresh(in.tofValid,in.tofUs,in.nowUs,config_.tofStaleUs))){safety_=SafetyState::Fault;safe(o,in.tofValid?StopReason::TofStale:StopReason::TofInvalid);return o;}
  if(needsGnss&&(!in.gnssValid||!fresh(in.gnssValid,in.gnssUs,in.nowUs,config_.gnssStaleUs)||!waypointCount_)){safety_=SafetyState::Fault;safe(o,in.gnssValid?StopReason::GnssStale:StopReason::GnssInvalid);return o;}
  if(manualMode){o.leftPrelimit=manual_.leftFront;o.rightPrelimit=manual_.rightFront;o.rearPrelimit=manual_.rearYaw;o.propulsionPrelimit=manual_.propulsion;}
  else {o.uPitch=config_.kpPitch*(config_.targetPitch-in.pitchRad)-config_.kdPitch*in.pitchRateRadS;o.uRoll=config_.kpRoll*(config_.targetRoll-in.rollRad)-config_.kdRoll*in.rollRateRadS;o.uHeight=config_.kpHeight*(config_.targetHeightM-in.tofM);const float common=o.uPitch+o.uHeight;o.leftPrelimit=common+o.uRoll;o.rightPrelimit=common-o.uRoll; if(mode_==ControlMode::HeadingHold||mode_==ControlMode::AutoWaypoint){if(mode_==ControlMode::AutoWaypoint){const Waypoint&w=waypoints_[activeWaypoint_];const float dn=w.northM-in.northM,de=w.eastM-in.eastM;o.waypointDistanceM=std::sqrt(dn*dn+de*de);o.targetYaw=std::atan2(de,dn);if(o.waypointDistanceM<=config_.waypointReachM){o.waypointReached=true;if(++activeWaypoint_>=waypointCount_){safety_=SafetyState::Disarmed;safe(o,StopReason::FinalWaypoint);return o;}}}else o.targetYaw=targetYaw_;o.uYaw=config_.kpYaw*wrap(o.targetYaw-in.yawRad)-config_.kdYaw*in.yawRateRadS;o.rearPrelimit=o.uYaw;} else o.rearPrelimit=manual_.rearYaw;o.propulsionPrelimit=(mode_==ControlMode::AutoWaypoint)?config_.autoPropulsion:manual_.propulsion;}
  if(!finite(o.leftPrelimit)||!finite(o.rightPrelimit)||!finite(o.rearPrelimit)||!finite(o.propulsionPrelimit)){safety_=SafetyState::Fault;safe(o,StopReason::NonFinite);return o;} o.leftFront=limit(o.leftPrelimit,previous_[0],o.saturated);o.rightFront=limit(o.rightPrelimit,previous_[1],o.saturated);o.rearYaw=limit(o.rearPrelimit,previous_[2],o.saturated);o.propulsion=limit(o.propulsionPrelimit,previous_[3],o.saturated);if(o.propulsion<0)o.propulsion=0;previous_[0]=o.leftFront;previous_[1]=o.rightFront;previous_[2]=o.rearYaw;previous_[3]=o.propulsion;o.physicalGate=false;return o; }
const char* safetyName(SafetyState x){switch(x){case SafetyState::Boot:return"BOOT";case SafetyState::Disarmed:return"DISARMED";case SafetyState::ArmedIdle:return"ARMED_IDLE";case SafetyState::Running:return"RUNNING";case SafetyState::EStop:return"E_STOP";default:return"FAULT";}} const char* modeName(ControlMode x){switch(x){case ControlMode::Manual:return"MANUAL";case ControlMode::AttitudeAssist:return"ATTITUDE_ASSIST";case ControlMode::HeadingHold:return"HEADING_HOLD";default:return"AUTO_WAYPOINT";}} const char* reasonName(StopReason x){switch(x){case StopReason::None:return"NONE";case StopReason::Stop:return"STOP";case StopReason::EStop:return"E_STOP";case StopReason::Heartbeat:return"HEARTBEAT";case StopReason::ManualTimeout:return"MANUAL_TIMEOUT";case StopReason::ImuInvalid:return"IMU_INVALID";case StopReason::ImuStale:return"IMU_STALE";case StopReason::TofInvalid:return"TOF_INVALID";case StopReason::TofStale:return"TOF_STALE";case StopReason::GnssInvalid:return"GNSS_INVALID";case StopReason::GnssStale:return"GNSS_STALE";case StopReason::VescFault:return"VESC_FAULT";case StopReason::NonFinite:return"NONFINITE";default:return"FINAL_WAYPOINT";}}
}  // namespace competition_shadow
