#include <assert.h>
#include <cstdio>
#include <cstring>
#include "boat_protocol.h"
#include "competition_command.h"
#include "competition_shadow.h"
#include "command_ingress.h"
using namespace competition_command;
struct Sink { uint8_t frames[8][boat::kMaxEncoded]{}; size_t length[8]{}; uint8_t count=0; };
static size_t write(const uint8_t* data,size_t n,void* context){auto*s=(Sink*)context;assert(s->count<8);memcpy(s->frames[s->count],data,n);s->length[s->count++]=n;return n;}
static boat::Frame decode(const uint8_t* data,size_t n){boat::Decoder d;boat::Frame f{};bool ok=false;for(size_t i=0;i<n;++i)if(d.feed(data[i],f))ok=true;assert(ok);return f;}
static boat::Frame ackFrame(const PendingCommand&e,uint8_t disposition,uint16_t reason,uint64_t applied){boat::ControlCommandAckPayload a{};a.requestId=e.requestId;a.commandSequence=e.commandSequence;a.commandType=e.type;a.disposition=disposition;a.reason=reason;a.appliedUs=applied;a.canonicalCrc=boat::canonicalCrc(&a,offsetof(boat::ControlCommandAckPayload,canonicalCrc));boat::Frame f{};f.header.type=(uint8_t)boat::Type::ControlCommandAck;f.header.length=sizeof(a);memcpy(f.payload,&a,sizeof(a));return f;}
static competition_shadow::SensorInput healthy(uint64_t t){competition_shadow::SensorInput x{};x.nowUs=t;x.safety=competition_shadow::AuthoritativeSafety::Running;x.heartbeat=x.imuValid=x.tofValid=x.gnssValid=true;x.heartbeatUs=x.imuUs=x.tofUs=x.gnssUs=t;x.tofM=1.2f;return x;}
int main(){
 Manager manager; Sink sink{}; competition_shadow::Controller xiao; competition_shadow::CommandIngress ingress;
 assert(manager.queueMode(0,10,100,1000,10000,7));assert(manager.service(0,write,&sink));auto f=decode(sink.frames[0],sink.length[0]);auto r=ingress.process(f,competition_shadow::AuthoritativeSafety::Disarmed,xiao,10);assert(r.result.ack==competition_shadow::Ack::Accepted);assert(manager.handleAck(ackFrame(manager.entries()[0],0,0,10),11));assert(manager.entries()[0].state==State::AckApplied);
 assert(manager.queueHeading(.3f,11,101,1001,10001,7));assert(manager.service(20,write,&sink));f=decode(sink.frames[1],sink.length[1]);r=ingress.process(f,competition_shadow::AuthoritativeSafety::Disarmed,xiao,20);assert(r.result.ack==competition_shadow::Ack::Accepted);assert(manager.handleAck(ackFrame(manager.entries()[1],0,0,20),21));assert(manager.entries()[1].state==State::AckApplied);
 assert(manager.queueManual(.2f,-.2f,.1f,.3f,12,102,1002,20000,7));assert(manager.service(100,write,&sink));f=decode(sink.frames[2],sink.length[2]);r=ingress.process(f,competition_shadow::AuthoritativeSafety::Running,xiao,100);assert(r.result.ack==competition_shadow::Ack::Accepted);assert(manager.service(100100,write,&sink));assert(manager.service(200100,write,&sink));assert(sink.length[2]==sink.length[3]&&sink.length[2]==sink.length[4]&&memcmp(sink.frames[2],sink.frames[3],sink.length[2])==0&&memcmp(sink.frames[2],sink.frames[4],sink.length[2])==0);f=decode(sink.frames[3],sink.length[3]);r=ingress.process(f,competition_shadow::AuthoritativeSafety::Running,xiao,100100);assert(r.result.ack==competition_shadow::Ack::Duplicate);f=decode(sink.frames[4],sink.length[4]);r=ingress.process(f,competition_shadow::AuthoritativeSafety::Running,xiao,200100);assert(r.result.ack==competition_shadow::Ack::Duplicate);const PendingCommand* manual=&manager.entries()[2];assert(manager.handleAck(ackFrame(*manual,2,0,100),200101));assert(manual->state==State::AckDuplicate);auto output=xiao.step(healthy(500101));assert(output.reason==competition_shadow::StopReason::ManualTimeout);assert(ingress.metrics().duplicates==2&&ingress.metrics().duplicateReapply==0&&xiao.physicalWriteCount()==0);
 assert(manager.queueHeading(.4f,13,103,1003,30000,7));assert(manager.service(300,write,&sink));assert(manager.service(100300,write,&sink));assert(manager.service(200300,write,&sink));manager.service(300300,write,&sink);const PendingCommand* timeout=&manager.entries()[3];assert(timeout->state==State::TimedOut&&timeout->transmissions==3);
 auto unmatched=ackFrame(*manual,0,0,1);auto* payload=(boat::ControlCommandAckPayload*)unmatched.payload;payload->requestId=999;payload->canonicalCrc=boat::canonicalCrc(payload,offsetof(boat::ControlCommandAckPayload,canonicalCrc));assert(manager.handleAck(unmatched,400));auto malformed=ackFrame(*manual,0,0,1);((boat::ControlCommandAckPayload*)malformed.payload)->canonicalCrc^=1;assert(manager.handleAck(malformed,401));const auto& d=manager.diagnostics();assert(d.initialTx==4&&d.retryTx==4&&d.timeouts==1&&d.ackMatched==3&&d.ackUnmatched==1&&d.ackMalformed==1&&d.manualRetries==2&&d.physicalWrites==0);std::puts("CORE_COMMAND_TRANSACTION_HOST_PASS types=68_69_70 retry_same_wire=ok duplicate_deadman=ok timeout=ok ack_matching=ok physical_writes=0");
}