#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <boat_protocol.h>
#include <proposal_min.h>
#include <waypoint_apply.h>
namespace {
constexpr uint32_t kMagic=0x424C4F47UL;
using SnapshotPayload=boat::ControlSnapshotPayload; using InaPayload=boat::InaStatusPayload; using VescPayload=boat::VescTelemetryPayload;
static_assert(sizeof(SnapshotPayload)==190,"snapshot wire size"); static_assert(sizeof(InaPayload)==32,"ina wire size"); static_assert(sizeof(VescPayload)==48,"vesc wire size");
void writeRecord(std::ofstream& out, boat::Type type, uint32_t& sequence, uint64_t timestamp, const void* payload, uint16_t length) { boat::Header header{boat::kVersion,(uint8_t)type,length,++sequence,7,timestamp,0}; uint8_t encoded[boat::kMaxEncoded]{}; const size_t encodedLength=boat::encode(header,(const uint8_t*)payload,encoded,sizeof(encoded)); assert(encodedLength>0); boat::Decoder decoder; boat::Frame decoded{}; bool got=false; for(size_t i=0;i<encodedLength;++i) if(decoder.feed(encoded[i],decoded)) got=true; assert(got&&decoder.crcErrors==0&&decoder.cobsErrors==0&&decoder.lengthErrors==0); assert(decoded.header.version==header.version&&decoded.header.type==header.type&&decoded.header.length==header.length&&decoded.header.sequence==header.sequence&&decoded.header.bootId==header.bootId&&decoded.header.sourceUs==header.sourceUs); assert(std::memcmp(decoded.payload,payload,length)==0); out.write(reinterpret_cast<const char*>(&kMagic),sizeof(kMagic)); out.write(reinterpret_cast<const char*>(&timestamp),sizeof(timestamp)); out.write(reinterpret_cast<const char*>(&decoded.header),sizeof(decoded.header)); out.write(reinterpret_cast<const char*>(decoded.payload),length); }
}
int main(int argc,char** argv){
 const char* path=argc>1?argv[1]:"min_shadow_30min.BIN"; constexpr uint64_t kDurationUs=1800ULL*1000000ULL,kPeriodUs=20000ULL; const uint64_t steps=kDurationUs/kPeriodUs; std::ofstream out(path,std::ios::binary); if(!out)return 2;
 proposal_min::Controller controller; proposal_min::ControlConfig cfg{}; cfg.leftFrontWing=proposal_min::ActuatorConfig{0,-1,1,1,1,false}; cfg.rightFrontWing=proposal_min::ActuatorConfig{0,-1,1,1,1,false}; cfg.rearYaw=proposal_min::ActuatorConfig{0,-1,1,1,1,false}; cfg.propulsion=proposal_min::ActuatorConfig{0,0,1,1,0.2f,false}; cfg.propulsionCommand=0.4f; cfg.propulsionStop=0;
 proposal_min::Waypoint route[]={{0.0f,0.0f},{4.0f,0.0f},{8.0f,2.0f},{12.0f,0.0f}}; uint16_t ranges[8]={1200,1201,1199,1202,1200,1201,1198,1200}; uint8_t status[8]={5,5,5,5,5,5,5,5};
 boat::WaypointSetPayload waypointSet{}; waypointSet.requestId=77; waypointSet.revision=1; waypointSet.action=1; waypointSet.count=4; waypointSet.reachRadiusM=0.5f; waypointSet.points[0]={35.0,139.0}; waypointSet.points[1]={35.00001,139.0}; waypointSet.points[2]={35.00002,139.00001}; waypointSet.points[3]={35.00003,139.0}; waypointSet.canonicalCrc=boat::canonicalCrc(&waypointSet,offsetof(boat::WaypointSetPayload,canonicalCrc)); proposal_min::WaypointGeo geo[4]{}; for(int i=0;i<4;++i){geo[i].latitudeDeg=waypointSet.points[i].latitudeDeg;geo[i].longitudeDeg=waypointSet.points[i].longitudeDeg;} proposal_min::WaypointStore store{}; proposal_min::WaypointRequest request{waypointSet.requestId,waypointSet.revision,waypointSet.action,waypointSet.count,waypointSet.reachRadiusM,geo}; auto waypointResult=proposal_min::applyWaypointSet(proposal_min::WaypointSafetyState::Disarmed,request,store); assert(waypointResult.status==proposal_min::WaypointApplyStatus::Accepted&&store.revision==1&&store.count==4); boat::WaypointAckPayload waypointAck{}; waypointAck.requestId=waypointSet.requestId; waypointAck.revision=store.revision; waypointAck.status=(uint8_t)waypointResult.status; waypointAck.reason=(uint8_t)waypointResult.reason; waypointAck.activeIndex=store.activeIndex; waypointAck.count=store.count; waypointAck.canonicalCrc=boat::canonicalCrc(&waypointAck,offsetof(boat::WaypointAckPayload,canonicalCrc));
 uint32_t sequence=0; writeRecord(out,boat::Type::WaypointSet,sequence,0,&waypointSet,sizeof(waypointSet)); writeRecord(out,boat::Type::WaypointAck,sequence,1,&waypointAck,sizeof(waypointAck)); uint64_t lastGnss=0,lastImu=0,lastTof=0,outputCount=0,runningNonzero=0,safeZero=0; uint32_t starts=0,stops=0,estops=0,heartbeatFaults=0,sensorFaults=0;
 for(uint64_t i=0;i<steps;++i){ const uint64_t now=(i+1)*kPeriodUs; const bool stop=(now==220000000ULL||now==400000000ULL||now==580000000ULL||now==740000000ULL||now==900000000ULL||now==1230000000ULL||now==1430000000ULL); const bool start=(i==0||now==240000000ULL||now==420000000ULL||now==600000000ULL||now==760000000ULL||now==920000000ULL||now==1250000000ULL||now==1450000000ULL); const bool estop=(now>=1200000000ULL&&now<1210000000ULL); const bool heartbeatOk=!(now>=1400000000ULL&&now<1410000000ULL); if(start)++starts;if(stop)++stops;if(estop)++estops;if(!heartbeatOk)++heartbeatFaults; const bool gnssFault=(now>=180000000ULL&&now<190000000ULL); const bool imuFault=(now>=360000000ULL&&now<370000000ULL); const bool imuNan=(now>=720000000ULL&&now<721000000ULL); const bool tofFault=(now>=540000000ULL&&now<550000000ULL); if(gnssFault||imuFault||imuNan||tofFault)++sensorFaults;
  proposal_min::Input in{}; in.nowUs=now;in.start=start;in.stop=stop;in.estop=estop;in.heartbeatOk=heartbeatOk; in.gnss={35.0+(now/1000000.0)*0.000001,139.0,1.2f,0.15f+0.4f*sinf((float)now/10000000.0f),now,!gnssFault};if(!gnssFault)lastGnss=now; in.imu={0.2f*sinf((float)now/15000000.0f),0.08f*sinf((float)now/11000000.0f),0.05f*cosf((float)now/13000000.0f),0.01f*cosf((float)now/15000000.0f),0.01f*cosf((float)now/11000000.0f),-0.01f*sinf((float)now/13000000.0f),now,!imuFault};if(imuNan){in.imu.yawRad=NAN;in.imu.valid=true;}if(!imuFault&&!imuNan)lastImu=now; in.tof={ranges,status,8,now,!tofFault};if(!tofFault)lastTof=now;in.waypoints=route;in.waypointCount=4;
  const proposal_min::Output o=controller.step(in,cfg);++outputCount;if(o.safety==proposal_min::Safety::Running&&o.propulsion>0)++runningNonzero;if(o.safety!=proposal_min::Safety::Running&&o.propulsion==0)++safeZero; SnapshotPayload s{};s.timestampUs=now;s.cycle=(uint32_t)i;s.waypointRevision=store.revision;s.gnssAgeUs=lastGnss?(uint32_t)(now-lastGnss):UINT32_MAX;s.imuAgeUs=lastImu?(uint32_t)(now-lastImu):UINT32_MAX;s.tofAgeUs=lastTof?(uint32_t)(now-lastTof):UINT32_MAX;s.latitudeDeg=in.gnss.latitudeDeg;s.longitudeDeg=in.gnss.longitudeDeg;s.targetWaypointLatitudeDeg=store.points[o.waypointIndex<store.count?o.waypointIndex:0].latitudeDeg;s.targetWaypointLongitudeDeg=store.points[o.waypointIndex<store.count?o.waypointIndex:0].longitudeDeg;s.speedMps=in.gnss.speedMps;s.gnssCourseRad=in.gnss.courseRad;s.rollRad=in.imu.rollRad;s.pitchRad=in.imu.pitchRad;s.yawRad=in.imu.yawRad;s.rollRateRadS=in.imu.rollRateRadS;s.pitchRateRadS=in.imu.pitchRateRadS;s.yawRateRadS=in.imu.yawRateRadS;s.tofRawMm=o.tofRawMm;s.tofFilteredM=o.tofFilteredM;s.heightErrorM=o.heightErrorM;s.uHeight=o.u_height;s.uPitch=o.u_pitch;s.uRoll=o.u_roll;s.uYaw=o.u_yaw;s.frontCommon=o.frontCommon;s.frontDifferential=o.frontDifferential;s.leftFrontWing=o.left_front_wing;s.rightFrontWing=o.right_front_wing;s.rearYaw=o.rear_yaw;s.propulsion=o.propulsion;s.leftPrelimit=o.leftPrelimit;s.rightPrelimit=o.rightPrelimit;s.rearYawPrelimit=o.rearYawPrelimit;s.propulsionPrelimit=o.propulsionPrelimit;s.gnssValid=o.gnssValid;s.imuValid=o.imuValid;s.tofValid=o.tofValid;s.heightValid=o.heightValid;s.waypointReached=o.waypointReached;s.outputValid=o.inputValid;s.state=(uint8_t)o.safety;s.safetyReason=o.stopReason;s.mode=start?2:1;s.activeWaypoint=o.waypointIndex; writeRecord(out,boat::Type::ControlSnapshot,sequence,now,&s,sizeof(s)); InaPayload ina{};ina.timestampUs=now+1;ina.ageUs=0;ina.valid=((now/1000000ULL)%240)<180;ina.errorCode=ina.valid?0:1;ina.busVoltageV=ina.valid?12.0f:NAN;ina.shuntVoltageV=ina.valid?0.01f:NAN;ina.currentA=ina.valid?1.0f:NAN;ina.powerW=ina.valid?12.0f:NAN;writeRecord(out,boat::Type::InaStatus,sequence,now+1,&ina,sizeof(ina)); VescPayload v{};v.timestampUs=now+2;v.ageUs=0;v.valid=((now/1000000ULL)%300)<220;v.mechanicalRpmValid=0;v.inputVoltageV=v.valid?24.0f:NAN;v.motorCurrentA=v.valid?2.0f:NAN;v.inputCurrentA=v.valid?1.0f:NAN;v.duty=v.valid?0.1f:NAN;v.erpm=v.valid?1000.0f+(float)(now/1000000ULL):NAN;v.mosTempC=v.valid?40.0f:NAN;v.motorTempC=v.valid?42.0f:NAN;v.tachometer=v.valid?(int32_t)(now/1000000ULL):0;writeRecord(out,boat::Type::VescTelemetry,sequence,now+2,&v,sizeof(v)); if((i%10000)==0)std::cerr<<"step="<<i<<"/"<<steps<<" state="<<(unsigned)s.state<<" prop="<<s.propulsion<<"\n";
 }
 out.close();const auto&m=controller.metrics();std::cout<<"MIN_SHADOW_LONG_PASS duration_s=1800 period_us="<<kPeriodUs<<" steps="<<steps<<" outputs="<<outputCount<<" starts="<<starts<<" stops="<<stops<<" estops="<<estops<<" heartbeat_fault_windows="<<heartbeatFaults<<" sensor_fault_samples="<<sensorFaults<<" running_nonzero_propulsion="<<runningNonzero<<" safe_zero_outputs="<<safeZero<<" transitions="<<m.stateTransitions<<" nan_inf="<<m.nanInf<<" deadline_miss="<<m.task.deadlineMiss<<" waypoint_ack=accepted\n";return outputCount==steps&&runningNonzero>0&&safeZero>0?0:3;
}