#include "competition_command.h"
#include <cmath>
#include <cstring>
namespace competition_command {
const char* stateName(State s){switch(s){case State::Empty:return "empty";case State::Queued:return "queued";case State::WaitingAck:return "waiting_ack";case State::AckApplied:return "ack_applied";case State::AckRejected:return "ack_rejected";case State::AckDuplicate:return "ack_duplicate";case State::ProtocolError:return "protocol_error";case State::TimedOut:return "timed_out";}return "unknown";}
PendingCommand* Manager::allocate(){for(uint8_t i=0;i<kSlots;++i)if(!entries_[i].valid)return &entries_[i];for(uint8_t i=0;i<kSlots;++i)if(entries_[i].state!=State::Queued&&entries_[i].state!=State::WaitingAck)return &entries_[i];++diagnostics_.queueOverflow;return nullptr;}
bool Manager::queue(uint8_t type,const void* payload,uint16_t payloadLength,uint32_t requestId,uint32_t sequence,uint32_t frameSequence,uint64_t sourceUs,uint32_t bootId){++diagnostics_.requests;PendingCommand* e=allocate();if(!e)return false;*e={};e->valid=true;e->state=State::Queued;e->type=type;e->requestId=requestId;e->commandSequence=sequence;e->frameSequence=frameSequence;e->sourceUs=sourceUs;e->payloadLength=payloadLength;memcpy(e->payload,payload,payloadLength);boat::Header h{boat::kVersion,type,payloadLength,frameSequence,bootId,sourceUs,0};const size_t n=boat::encode(h,e->payload,e->wire,sizeof(e->wire));if(!n){e->valid=false;++diagnostics_.validationRejects;return false;}e->wireLength=(uint16_t)n;++diagnostics_.queued;return true;}
bool Manager::queueMode(uint8_t mode,uint32_t id,uint32_t seq,uint32_t frameSeq,uint64_t source,uint32_t boot){if(mode>3){++diagnostics_.validationRejects;return false;}boat::ControlModeCommandPayload p{};p.protocolVersion=boat::kVersion;p.mode=mode;p.requestId=id;p.commandSequence=seq;p.sourceUs=source;p.canonicalCrc=boat::canonicalCrc(&p,offsetof(boat::ControlModeCommandPayload,canonicalCrc));return queue((uint8_t)boat::Type::ControlModeCommand,&p,sizeof(p),id,seq,frameSeq,source,boot);}
bool Manager::queueManual(float l,float r,float y,float p,uint32_t id,uint32_t seq,uint32_t frameSeq,uint64_t source,uint32_t boot){if(!std::isfinite(l)||!std::isfinite(r)||!std::isfinite(y)||!std::isfinite(p)||l<-1||l>1||r<-1||r>1||y<-1||y>1||p<0||p>1){++diagnostics_.validationRejects;return false;}boat::ManualCommandPayload q{};q.protocolVersion=boat::kVersion;q.requestId=id;q.commandSequence=seq;q.sourceUs=source;q.leftFrontWing=l;q.rightFrontWing=r;q.rearYaw=y;q.propulsion=p;q.canonicalCrc=boat::canonicalCrc(&q,offsetof(boat::ManualCommandPayload,canonicalCrc));++diagnostics_.manualSamples;return queue((uint8_t)boat::Type::ManualCommand,&q,sizeof(q),id,seq,frameSeq,source,boot);}
bool Manager::queueHeading(float target,uint32_t id,uint32_t seq,uint32_t frameSeq,uint64_t source,uint32_t boot){if(!std::isfinite(target)){++diagnostics_.validationRejects;return false;}boat::HeadingTargetPayload p{};p.protocolVersion=boat::kVersion;p.requestId=id;p.commandSequence=seq;p.sourceUs=source;p.targetYawRad=target;p.canonicalCrc=boat::canonicalCrc(&p,offsetof(boat::HeadingTargetPayload,canonicalCrc));return queue((uint8_t)boat::Type::HeadingTarget,&p,sizeof(p),id,seq,frameSeq,source,boot);}
bool Manager::service(uint64_t now,size_t(*write)(const uint8_t*,size_t,void*),void* context){bool any=false;for(uint8_t i=0;i<kSlots;++i){PendingCommand&e=entries_[i];if(!e.valid)continue;bool due=e.state==State::Queued||(e.state==State::WaitingAck&&now>=e.ackDeadlineUs);if(!due)continue;if(e.state==State::WaitingAck&&e.transmissions>=config_.maxTransmissions){e.state=State::TimedOut;++diagnostics_.timeouts;continue;}if(e.transmissions>=config_.maxTransmissions){e.state=State::TimedOut;++diagnostics_.timeouts;continue;}const bool retry=e.transmissions>0;const size_t sent=write(e.wire,e.wireLength,context);if(sent!=e.wireLength)continue;if(!e.initialTxUs)e.initialTxUs=now;e.lastTxUs=now;++e.transmissions;e.ackDeadlineUs=now+config_.ackTimeoutUs;e.state=State::WaitingAck;if(retry){++diagnostics_.retryTx;if(e.type==(uint8_t)boat::Type::ManualCommand)++diagnostics_.manualRetries;}else ++diagnostics_.initialTx;any=true;}return any;}
bool Manager::handleAck(const boat::Frame& frame,uint64_t){if((boat::Type)frame.header.type!=boat::Type::ControlCommandAck)return false;if(frame.header.length!=sizeof(boat::ControlCommandAckPayload)){++diagnostics_.ackMalformed;return true;}boat::ControlCommandAckPayload a{};memcpy(&a,frame.payload,sizeof(a));if(a.canonicalCrc!=boat::canonicalCrc(&a,offsetof(boat::ControlCommandAckPayload,canonicalCrc))||a.commandType<(uint8_t)boat::Type::ControlModeCommand||a.commandType>(uint8_t)boat::Type::HeadingTarget||a.disposition>4){++diagnostics_.ackMalformed;return true;}++diagnostics_.ackReceived;for(uint8_t i=0;i<kSlots;++i){PendingCommand&e=entries_[i];if(!e.valid||e.requestId!=a.requestId||e.commandSequence!=a.commandSequence||e.type!=a.commandType)continue;if(e.state!=State::WaitingAck){++diagnostics_.ackLate;return true;}++diagnostics_.ackMatched;e.ackDisposition=a.disposition;e.ackReason=a.reason;e.xiaoAppliedUs=a.appliedUs;if(a.disposition==0){e.state=State::AckApplied;++diagnostics_.ackApplied;}else if(a.disposition==1){e.state=State::AckRejected;++diagnostics_.ackRejected;}else if(a.disposition==2){e.state=State::AckDuplicate;++diagnostics_.ackDuplicate;}else if(a.disposition==3){e.state=State::ProtocolError;++diagnostics_.protocolConflict;}else {e.state=State::ProtocolError;++diagnostics_.stale;}return true;}++diagnostics_.ackUnmatched;return true;}
bool Manager::hasPendingManual()const{for(const auto&e:entries_)if(e.valid&&e.type==(uint8_t)boat::Type::ManualCommand&&(e.state==State::Queued||e.state==State::WaitingAck))return true;return false;}
} // namespace competition_command